Генерируем ссылки, по которым будем собирать адреса объявлений

In [42]:
base_link = "https://www.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&region=1&object_type%5B0%5D=1"

links = []

def generate_range(start, end, step):
    """Генерирует ссылки для диапазона цен"""
    curr = start
    while curr < end:
        #верхняя граница-1
        next_val = min(curr + step, end)
        max_p = next_val - 1
        
        url = f"{base_link}&minprice={curr}&maxprice={max_p}"
        links.append(url)
        
        curr = next_val
    print(len(links))
        
links.append('url')

#все до 6 млн берем вместе
generate_range(0, 6000000, 6000000)

#самый маленький шаг для минимума
generate_range(6_000_000, 25_000_000, 500_000)

#квартриры подороже - шаг 1 млн
generate_range(25_000_000, 50_000_000, 1_000_000)

#элита - шаг 5 млн
generate_range(50_000_000, 200_000_000, 5_000_000)

#элита покруче - шаг 50 млн
generate_range(200_000_000, 1_000_000_000, 50_000_000)


#дописываю остаток от 1 млрд
url = f"{base_link}&minprice=1000000000"
links.append(url)

#сохраняем полученные файлы
filename = "links.csv"
with open(filename, "w", encoding="utf-8") as f:
    for link in links:
        f.write(link + "\n")

print(f"Сгенерировано {len(links)-1} ссылок.")
print(f"Сохранено в файл: {filename}")

2
40
65
95
111
Сгенерировано 112 ссылок.
Сохранено в файл: links.csv

Тут определяем, сколько страниц для каждой ссылки нужно

In [43]:
import time
import pandas as pd
import os
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import re
import math #для округлвверх

FILENAME = "links.csv"
OUTPUT_FILE = "checked_links.csv"

options = webdriver.ChromeOptions()
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
results = []

def save_data(data_list, filename):
    if not data_list:
        return
    df = pd.DataFrame(data_list)
    header = not os.path.exists(filename)
    df.to_csv(filename, mode='a', index=False, header=header, encoding='utf-8-sig')
    print(f"Сохранено {len(data_list)} новых записей в {filename}")

try:
    df = pd.read_csv(FILENAME)
    links = df['url'].dropna().tolist()
    print(f"Всего ссылок в файле: {len(links)}")

    for i, url in enumerate(links):
        driver.get(url)
        time.sleep(1)
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        header = soup.find('div', {'data-name': 'SummaryHeader'})
        if header:
            text = header.get_text()
            #регуляркой ищем "Найдено N объявлений"
            match = re.search(r'Найдено\s+([\d\s]+)', text)
            if match:
                clean_number = match.group(1).replace(' ', '').replace('\xa0', '')
        else:
            clean_number = 0
        results.append({
                'url': url,
                'total_ads': clean_number,
                'cnt_pages': math.ceil(int(clean_number)/28)
            })
        
        if (i+1) % 10 == 0:
            pd.DataFrame(results).to_csv(OUTPUT_FILE, index=False)
            print(f'сохранено {i+1} ссылок.')

finally:
    driver.quit()
    #итог
    final_df = pd.DataFrame(results)
    final_df.to_csv(OUTPUT_FILE, index=False)
    print('все ссылки обработаны')

Всего ссылок в файле: 111
сохранено 10 ссылок.
сохранено 20 ссылок.
сохранено 30 ссылок.
сохранено 40 ссылок.
сохранено 50 ссылок.
сохранено 60 ссылок.
сохранено 70 ссылок.
сохранено 80 ссылок.
сохранено 90 ссылок.
сохранено 100 ссылок.
сохранено 110 ссылок.
все ссылки обработаны

### Собираем адреса объявлений

In [111]:
import time
import pandas as pd
import os
import winsound
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup

#Настройки браузера

target_links = pd.read_csv("checked_links.csv")  # Файл с диапазонами и кол-вом страниц
FILENAME = "cian_final_data.csv" 
'''
options = webdriver.ChromeOptions()
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
'''
#настройки браузера
options = webdriver.ChromeOptions()
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument("--log-level=3")
options.page_load_strategy = 'eager'

#пытаемся обойти блокировку vpn (это не сработало)
#options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

prefs = {"profile.managed_default_content_settings.images": 2}
options.add_experimental_option("prefs", prefs)


driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

results = []

#-------------БЛОК ФУНКЦИЙ------------------------

#сохраняет данные и выводит об этом инфу
def save_data(data_list, filename):
    if not data_list:
        return
    df = pd.DataFrame(data_list)
    header = not os.path.exists(filename)
    df.to_csv(filename, mode='a', index=False, header=header, encoding='utf-8-sig')
    print(f"   -> Сохранено {len(data_list)} новых записей в {filename}")


#-------------ОСНОВНОЙ БЛОК------------------------
try:
    for i, row in target_links.iterrows():
        base_url = row['url']
        max_pages = int(row['cnt_pages']) 
        
        #скип пустых диапазонов (вдруг)
        if max_pages == 0:
            continue
            
        print(f"\n>>> Ссылка [{i+1}/{len(target_links)}] (страниц: {max_pages})")

        # цикл по страницам внутри ссылки
        for page_num in range(1, max_pages + 1):
            
            #ссылка для перехода
            if page_num == 1:
                current_url = base_url
            else:
                current_url = base_url + f"&p={page_num}"
            
            print(f"    страница {page_num} из {max_pages}")
            
            try: 
                #print(f"Вход: {current_url}")
                driver.get(current_url)
                
                #время на загрузку страницы, на всякий случай
                time.sleep(2)
            
                #постранично обрабатываем все доступные по запросу страницы (сверху фикс - были взяты все вторички Москвы)
                #print(f"\n--- Обработка страницы {page_num} ---")
                
                soup = BeautifulSoup(driver.page_source, 'html.parser')
                offers = soup.find_all('article')
        
                for offer in offers:
                    try:
                        #цена объекта
                        price_text = "0"
                        price_elem = offer.find('span', {'data-mark': 'MainPrice'})
                        if price_elem:
                            price_text = price_elem.get_text(strip=True)
                        else:
                            candidates = offer.find_all(string=lambda t: '₽' in t if t else False)
                            if candidates:
                                price_text = candidates[0]
        
                        clean_price = "".join([c for c in price_text if c.isdigit()])
                        
                        #ссылка на объявление
                        link_tag = offer.find('a', href=True)
                        link = link_tag['href'] if link_tag else "Нет ссылки"
        
                        #адрес
                        geo_labels = offer.find_all('a', {'data-name': 'GeoLabel'})
                        address = ", ".join([g.text.strip() for g in geo_labels])

                        
                        if not address:
                            title_div = offer.find('div', {'data-name': 'GeneralInfoSectionRowComponent'})
                            address = title_div.get_text(strip=True) if title_div else "Адрес не найден"

                        #аукцион
                        auction_tag = offer.find(string=re.compile(r"Аукцион"))
                        if auction_tag:
                            marker_text = True
                        else:
                            marker_text = False
                            
                        
                        results.append({
                            'price': clean_price,
                            'address': address,
                            'url': link,
                            'auction': marker_text
                        })
                    except Exception as e:
                        continue
                
                #----сохраняем инфу каждые 5 страниц---
                if page_num % 5 == 0:
                    save_data(results, FILENAME)
                    results = [] 
        
                
            except Exception as e:
                print(f"Ошибка при обработке страницы: {e}")
                time.sleep(5)
    time.sleep(1.5)

finally:
    if results:
        save_data(results, FILENAME)
    
    driver.quit()
    print("\nБраузер закрыт. Сбор завершен.")

>>> Ссылка [1/111] (страниц: 29)
    страница 1 из 29
    страница 2 из 29
    страница 3 из 29
    страница 4 из 29
    страница 5 из 29
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 6 из 29
    страница 7 из 29
    страница 8 из 29
    страница 9 из 29
    страница 10 из 29
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 29
    страница 12 из 29
    страница 13 из 29
    страница 14 из 29
    страница 15 из 29
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 29
    страница 17 из 29
    страница 18 из 29
    страница 19 из 29
    страница 20 из 29
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 29
    страница 22 из 29
    страница 23 из 29
    страница 24 из 29
    страница 25 из 29
   -> Сохранено 137 новых записей в cian_final_data.csv
    страница 26 из 29
    страница 27 из 29
    страница 28 из 29
    страница 29 из 29

>>> Ссылка [2/111] (страниц: 10)
    страница 1 из 10
    страница 2 из 10
    страница 3 из 10
    страница 4 из 10
    страница 5 из 10
   -> Сохранено 246 новых записей в cian_final_data.csv
    страница 6 из 10
    страница 7 из 10
    страница 8 из 10
    страница 9 из 10
    страница 10 из 10
   -> Сохранено 137 новых записей в cian_final_data.csv

>>> Ссылка [3/111] (страниц: 8)
    страница 1 из 8
    страница 2 из 8
    страница 3 из 8
    страница 4 из 8
    страница 5 из 8
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 6 из 8
    страница 7 из 8
    страница 8 из 8

>>> Ссылка [4/111] (страниц: 8)
    страница 1 из 8
    страница 2 из 8
    страница 3 из 8
    страница 4 из 8
    страница 5 из 8
   -> Сохранено 221 новых записей в cian_final_data.csv
    страница 6 из 8
    страница 7 из 8
    страница 8 из 8

>>> Ссылка [5/111] (страниц: 9)
    страница 1 из 9
    страница 2 из 9
    страница 3 из 9
    страница 4 из 9
    страница 5 из 9
   -> Сохранено 221 новых записей в cian_final_data.csv
    страница 6 из 9
    страница 7 из 9
    страница 8 из 9
    страница 9 из 9

>>> Ссылка [6/111] (страниц: 11)
    страница 1 из 11
    страница 2 из 11
    страница 3 из 11
    страница 4 из 11
    страница 5 из 11
   -> Сохранено 249 новых записей в cian_final_data.csv
    страница 6 из 11
    страница 7 из 11
    страница 8 из 11
    страница 9 из 11
    страница 10 из 11
   -> Сохранено 137 новых записей в cian_final_data.csv
    страница 11 из 11

>>> Ссылка [7/111] (страниц: 13)
    страница 1 из 13
    страница 2 из 13
    страница 3 из 13
    страница 4 из 13
    страница 5 из 13
   -> Сохранено 168 новых записей в cian_final_data.csv
    страница 6 из 13
    страница 7 из 13
    страница 8 из 13
    страница 9 из 13
    страница 10 из 13
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 13
    страница 12 из 13
    страница 13 из 13

>>> Ссылка [8/111] (страниц: 13)
    страница 1 из 13
    страница 2 из 13
    страница 3 из 13
    страница 4 из 13
    страница 5 из 13
   -> Сохранено 221 новых записей в cian_final_data.csv
    страница 6 из 13
    страница 7 из 13
    страница 8 из 13
    страница 9 из 13
    страница 10 из 13
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 13
    страница 12 из 13
    страница 13 из 13

>>> Ссылка [9/111] (страниц: 20)
    страница 1 из 20
    страница 2 из 20
    страница 3 из 20
    страница 4 из 20
    страница 5 из 20
   -> Сохранено 221 новых записей в cian_final_data.csv
    страница 6 из 20
    страница 7 из 20
    страница 8 из 20
    страница 9 из 20
    страница 10 из 20
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 20
    страница 12 из 20
    страница 13 из 20
    страница 14 из 20
    страница 15 из 20
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 20
    страница 17 из 20
    страница 18 из 20
    страница 19 из 20
    страница 20 из 20
   -> Сохранено 137 новых записей в cian_final_data.csv

>>> Ссылка [10/111] (страниц: 18)
    страница 1 из 18
    страница 2 из 18
    страница 3 из 18
    страница 4 из 18
    страница 5 из 18
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 6 из 18
    страница 7 из 18
    страница 8 из 18
    страница 9 из 18
    страница 10 из 18
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 18
    страница 12 из 18
    страница 13 из 18
    страница 14 из 18
    страница 15 из 18
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 18
    страница 17 из 18
    страница 18 из 18

>>> Ссылка [11/111] (страниц: 25)
    страница 1 из 25
    страница 2 из 25
    страница 3 из 25
    страница 4 из 25
    страница 5 из 25
   -> Сохранено 221 новых записей в cian_final_data.csv
    страница 6 из 25
    страница 7 из 25
    страница 8 из 25
    страница 9 из 25
    страница 10 из 25
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 25
    страница 12 из 25
    страница 13 из 25
    страница 14 из 25
    страница 15 из 25
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 25
    страница 17 из 25
    страница 18 из 25
    страница 19 из 25
    страница 20 из 25
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 25
    страница 22 из 25
    страница 23 из 25
    страница 24 из 25
    страница 25 из 25
   -> Сохранено 137 новых записей в cian_final_data.csv

>>> Ссылка [12/111] (страниц: 22)
    страница 1 из 22
    страница 2 из 22
    страница 3 из 22
    страница 4 из 22
    страница 5 из 22
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 6 из 22
    страница 7 из 22
    страница 8 из 22
    страница 9 из 22
    страница 10 из 22
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 22
    страница 12 из 22
    страница 13 из 22
    страница 14 из 22
    страница 15 из 22
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 22
    страница 17 из 22
    страница 18 из 22
    страница 19 из 22
    страница 20 из 22
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 22
    страница 22 из 22

>>> Ссылка [13/111] (страниц: 29)
    страница 1 из 29
    страница 2 из 29
    страница 3 из 29
    страница 4 из 29
    страница 5 из 29
   -> Сохранено 193 новых записей в cian_final_data.csv
    страница 6 из 29
    страница 7 из 29
    страница 8 из 29
    страница 9 из 29
    страница 10 из 29
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 29
    страница 12 из 29
    страница 13 из 29
    страница 14 из 29
    страница 15 из 29
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 29
    страница 17 из 29
    страница 18 из 29
    страница 19 из 29
    страница 20 из 29
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 29
    страница 22 из 29
    страница 23 из 29
    страница 24 из 29
    страница 25 из 29
   -> Сохранено 137 новых записей в cian_final_data.csv
    страница 26 из 29
    страница 27 из 29
    страница 28 из 29
    страница 29 из 29

>>> Ссылка [14/111] (страниц: 24)
    страница 1 из 24
    страница 2 из 24
    страница 3 из 24
    страница 4 из 24
    страница 5 из 24
   -> Сохранено 249 новых записей в cian_final_data.csv
    страница 6 из 24
    страница 7 из 24
    страница 8 из 24
    страница 9 из 24
    страница 10 из 24
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 24
    страница 12 из 24
    страница 13 из 24
    страница 14 из 24
    страница 15 из 24
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 24
    страница 17 из 24
    страница 18 из 24
    страница 19 из 24
    страница 20 из 24
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 24
    страница 22 из 24
    страница 23 из 24
    страница 24 из 24

>>> Ссылка [15/111] (страниц: 34)
    страница 1 из 34
    страница 2 из 34
    страница 3 из 34
    страница 4 из 34
    страница 5 из 34
   -> Сохранено 250 новых записей в cian_final_data.csv
    страница 6 из 34
    страница 7 из 34
    страница 8 из 34
    страница 9 из 34
    страница 10 из 34
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 34
    страница 12 из 34
    страница 13 из 34
    страница 14 из 34
    страница 15 из 34
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 34
    страница 17 из 34
    страница 18 из 34
    страница 19 из 34
    страница 20 из 34
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 34
    страница 22 из 34
    страница 23 из 34
    страница 24 из 34
    страница 25 из 34
   -> Сохранено 137 новых записей в cian_final_data.csv
    страница 26 из 34
    страница 27 из 34
    страница 28 из 34
    страница 29 из 34
    страница 30 из 34
   -> Сохранено 139 новых записей в cian_final_data.csv
    страница 31 из 34
    страница 32 из 34
    страница 33 из 34
    страница 34 из 34

>>> Ссылка [16/111] (страниц: 23)
    страница 1 из 23
    страница 2 из 23
    страница 3 из 23
    страница 4 из 23
    страница 5 из 23
   -> Сохранено 249 новых записей в cian_final_data.csv
    страница 6 из 23
    страница 7 из 23
    страница 8 из 23
    страница 9 из 23
    страница 10 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 23
    страница 12 из 23
    страница 13 из 23
    страница 14 из 23
    страница 15 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 23
    страница 17 из 23
    страница 18 из 23
    страница 19 из 23
    страница 20 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 23
    страница 22 из 23
    страница 23 из 23

>>> Ссылка [17/111] (страниц: 34)
    страница 1 из 34
    страница 2 из 34
    страница 3 из 34
    страница 4 из 34
    страница 5 из 34
   -> Сохранено 224 новых записей в cian_final_data.csv
    страница 6 из 34
    страница 7 из 34
    страница 8 из 34
    страница 9 из 34
    страница 10 из 34
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 34
    страница 12 из 34
    страница 13 из 34
    страница 14 из 34
    страница 15 из 34
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 34
    страница 17 из 34
    страница 18 из 34
    страница 19 из 34
    страница 20 из 34
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 34
    страница 22 из 34
    страница 23 из 34
    страница 24 из 34
    страница 25 из 34
   -> Сохранено 137 новых записей в cian_final_data.csv
    страница 26 из 34
    страница 27 из 34
    страница 28 из 34
    страница 29 из 34
    страница 30 из 34
   -> Сохранено 139 новых записей в cian_final_data.csv
    страница 31 из 34
    страница 32 из 34
    страница 33 из 34
    страница 34 из 34

>>> Ссылка [18/111] (страниц: 23)
    страница 1 из 23
    страница 2 из 23
    страница 3 из 23
    страница 4 из 23
    страница 5 из 23
   -> Сохранено 249 новых записей в cian_final_data.csv
    страница 6 из 23
    страница 7 из 23
    страница 8 из 23
    страница 9 из 23
    страница 10 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 23
    страница 12 из 23
    страница 13 из 23
    страница 14 из 23
    страница 15 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 23
    страница 17 из 23
    страница 18 из 23
    страница 19 из 23
    страница 20 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 23
    страница 22 из 23
    страница 23 из 23

>>> Ссылка [19/111] (страниц: 34)
    страница 1 из 34
    страница 2 из 34
    страница 3 из 34
    страница 4 из 34
    страница 5 из 34
   -> Сохранено 221 новых записей в cian_final_data.csv
    страница 6 из 34
    страница 7 из 34
    страница 8 из 34
    страница 9 из 34
    страница 10 из 34
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 34
    страница 12 из 34
    страница 13 из 34
    страница 14 из 34
    страница 15 из 34
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 34
    страница 17 из 34
    страница 18 из 34
    страница 19 из 34
    страница 20 из 34
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 34
    страница 22 из 34
    страница 23 из 34
    страница 24 из 34
    страница 25 из 34
   -> Сохранено 137 новых записей в cian_final_data.csv
    страница 26 из 34
    страница 27 из 34
    страница 28 из 34
    страница 29 из 34
    страница 30 из 34
   -> Сохранено 139 новых записей в cian_final_data.csv
    страница 31 из 34
    страница 32 из 34
    страница 33 из 34
    страница 34 из 34

>>> Ссылка [20/111] (страниц: 25)
    страница 1 из 25
    страница 2 из 25
    страница 3 из 25
    страница 4 из 25
    страница 5 из 25
   -> Сохранено 248 новых записей в cian_final_data.csv
    страница 6 из 25
    страница 7 из 25
    страница 8 из 25
    страница 9 из 25
    страница 10 из 25
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 25
    страница 12 из 25
    страница 13 из 25
    страница 14 из 25
    страница 15 из 25
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 25
    страница 17 из 25
    страница 18 из 25
    страница 19 из 25
    страница 20 из 25
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 25
    страница 22 из 25
    страница 23 из 25
    страница 24 из 25
    страница 25 из 25
   -> Сохранено 137 новых записей в cian_final_data.csv

>>> Ссылка [21/111] (страниц: 33)
    страница 1 из 33
    страница 2 из 33
    страница 3 из 33
    страница 4 из 33
    страница 5 из 33
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 6 из 33
    страница 7 из 33
    страница 8 из 33
    страница 9 из 33
    страница 10 из 33
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 33
    страница 12 из 33
    страница 13 из 33
    страница 14 из 33
    страница 15 из 33
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 33
    страница 17 из 33
    страница 18 из 33
    страница 19 из 33
    страница 20 из 33
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 33
    страница 22 из 33
    страница 23 из 33
    страница 24 из 33
    страница 25 из 33
   -> Сохранено 137 новых записей в cian_final_data.csv
    страница 26 из 33
    страница 27 из 33
    страница 28 из 33
    страница 29 из 33
    страница 30 из 33
   -> Сохранено 138 новых записей в cian_final_data.csv
    страница 31 из 33
    страница 32 из 33
    страница 33 из 33

>>> Ссылка [22/111] (страниц: 23)
    страница 1 из 23
    страница 2 из 23
    страница 3 из 23
    страница 4 из 23
    страница 5 из 23
   -> Сохранено 221 новых записей в cian_final_data.csv
    страница 6 из 23
    страница 7 из 23
    страница 8 из 23
    страница 9 из 23
    страница 10 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 23
    страница 12 из 23
    страница 13 из 23
    страница 14 из 23
    страница 15 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 23
    страница 17 из 23
    страница 18 из 23
    страница 19 из 23
    страница 20 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 23
    страница 22 из 23
    страница 23 из 23

>>> Ссылка [23/111] (страниц: 32)
    страница 1 из 32
    страница 2 из 32
    страница 3 из 32
    страница 4 из 32
    страница 5 из 32
   -> Сохранено 221 новых записей в cian_final_data.csv
    страница 6 из 32
    страница 7 из 32
    страница 8 из 32
    страница 9 из 32
    страница 10 из 32
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 32
    страница 12 из 32
    страница 13 из 32
    страница 14 из 32
    страница 15 из 32
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 32
    страница 17 из 32
    страница 18 из 32
    страница 19 из 32
    страница 20 из 32
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 32
    страница 22 из 32
    страница 23 из 32
    страница 24 из 32
    страница 25 из 32
   -> Сохранено 137 новых записей в cian_final_data.csv
    страница 26 из 32
    страница 27 из 32
    страница 28 из 32
    страница 29 из 32
    страница 30 из 32
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 31 из 32
    страница 32 из 32

>>> Ссылка [24/111] (страниц: 24)
    страница 1 из 24
    страница 2 из 24
    страница 3 из 24
    страница 4 из 24
    страница 5 из 24
   -> Сохранено 198 новых записей в cian_final_data.csv
    страница 6 из 24
    страница 7 из 24
    страница 8 из 24
    страница 9 из 24
    страница 10 из 24
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 24
    страница 12 из 24
    страница 13 из 24
    страница 14 из 24
    страница 15 из 24
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 24
    страница 17 из 24
    страница 18 из 24
    страница 19 из 24
    страница 20 из 24
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 24
    страница 22 из 24
    страница 23 из 24
    страница 24 из 24

>>> Ссылка [25/111] (страниц: 27)
    страница 1 из 27
    страница 2 из 27
    страница 3 из 27
    страница 4 из 27
    страница 5 из 27
   -> Сохранено 248 новых записей в cian_final_data.csv
    страница 6 из 27
    страница 7 из 27
    страница 8 из 27
    страница 9 из 27
    страница 10 из 27
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 27
    страница 12 из 27
    страница 13 из 27
    страница 14 из 27
    страница 15 из 27
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 27
    страница 17 из 27
    страница 18 из 27
    страница 19 из 27
    страница 20 из 27
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 27
    страница 22 из 27
    страница 23 из 27
    страница 24 из 27
    страница 25 из 27
   -> Сохранено 137 новых записей в cian_final_data.csv
    страница 26 из 27
    страница 27 из 27

>>> Ссылка [26/111] (страниц: 23)
    страница 1 из 23
    страница 2 из 23
    страница 3 из 23
    страница 4 из 23
    страница 5 из 23
   -> Сохранено 197 новых записей в cian_final_data.csv
    страница 6 из 23
    страница 7 из 23
    страница 8 из 23
    страница 9 из 23
    страница 10 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 23
    страница 12 из 23
    страница 13 из 23
    страница 14 из 23
    страница 15 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 23
    страница 17 из 23
    страница 18 из 23
    страница 19 из 23
    страница 20 из 23
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 23
    страница 22 из 23
    страница 23 из 23

>>> Ссылка [27/111] (страниц: 26)
    страница 1 из 26
    страница 2 из 26
    страница 3 из 26
    страница 4 из 26
    страница 5 из 26
   -> Сохранено 221 новых записей в cian_final_data.csv
    страница 6 из 26
    страница 7 из 26
    страница 8 из 26
    страница 9 из 26
    страница 10 из 26
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 11 из 26
    страница 12 из 26
    страница 13 из 26
    страница 14 из 26
    страница 15 из 26
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 16 из 26
    страница 17 из 26
    страница 18 из 26
    страница 19 из 26
    страница 20 из 26
   -> Сохранено 140 новых записей в cian_final_data.csv
    страница 21 из 26
    страница 22 из 26
    страница 23 из 26
    страница 24 из 26
    страница 25 из 26
   -> Сохранено 137 новых записей в cian_final_data.csv
    страница 26 из 26

>>> Ссылка [28/111] (страниц: 16)
    страница 1 из 16
    страница 2 из 16
    страница 3 из 16
    страница 4 из 16
    страница 5 из 16
   -> Сохранено 165 новых записей в cian_final_data.csv

In [112]:
df_urls = pd.read_csv("cian_final_data.csv")
print(f'старый файл: {df_urls.shape}')
df_urls = df_urls.drop_duplicates()
print(f'новый файл: {df_urls.shape}')
print(f'уникальных строк - {df_urls.url.nunique()}')

print('\n', 'дубликаты по url:', df_urls[df_urls.duplicated(subset=['url'], keep=False)])

FILENAME = "cian_urls_wo_duplicates.csv" 
df_urls.to_csv(FILENAME, mode='w', index=False, encoding='utf-8-sig')
print(f'Дубликаты удалены. Файл сохранен в {FILENAME}. Кол-во ссылок: {len(df_urls.url)}')

старый файл: (41762, 4)
новый файл: (38700, 4)
уникальных строк - 38700

 дубликаты по url: Empty DataFrame
Columns: [price, address, url, auction]
Index: []
Дубликаты удалены. Файл сохранен в cian_urls_wo_duplicates.csv. Кол-во ссылок: 38700

### Разведка данных - проверяем, какие атрибуты вообще бывают указаны на странице, чтобы хранить максимальное количество характеристик

In [72]:
import time
import pandas as pd
import os
import winsound
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup

INPUT_FILE = "cian_urls_wo_duplicates.csv" #смотрим файл со ссылками, который создали ранее
LINKS_TO_CHECK = 20                #сколько проверяем ссылок

#собираем ссылки
try:
    df = pd.read_csv(INPUT_FILE)
    links = df['url'].dropna().tolist()
    print(f"Всего ссылок в файле: {len(links)}. Проверим первые {LINKS_TO_CHECK}.")
except FileNotFoundError:
    print(f"Файл {INPUT_FILE} не найден.")
    exit()

#запускаем браузер
options = webdriver.ChromeOptions()
options.add_argument("--disable-blink-features=AutomationControlled")
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

#словарь для доступных полей
unique_fields = {}
#print(links)
#print(len(links))
#print('---------')
#print(links[20:LINKS_TO_CHECK])

try:
    
    for i, url in enumerate(links[:LINKS_TO_CHECK]):
        if "cian.ru" not in str(url):
            continue

        print(f"Заходим [{i+1}/{LINKS_TO_CHECK}]: {url}")
        
        try:
            driver.get(url)
            soup = BeautifulSoup(driver.page_source, 'html.parser')

            #все стандартные блоки атрибутов лежат в блоке OfferSummaryInfoItem
            items = soup.find_all('div', {'data-name': 'OfferSummaryInfoItem'})
            
            
            for item in items:
                texts = item.find_all('p')
                if len(texts) >= 2:
                    field_name = texts[0].get_text(strip=True)
                    example_value = texts[1].get_text(strip=True)
                    
                    #если поля нет в словаре пока, то добавляем его туда
                    if field_name not in unique_fields:
                        unique_fields[field_name] = example_value
                        print(f"    Новое поле: '{field_name}' (Пример: {example_value})")

        except Exception as e:
            print(f"Ошибка: {e}")
            continue

finally:
    driver.quit()

    print("\n" + "="*40)
    print("ИТОГОВЫЙ СПИСОК ДОСТУПНЫХ ПОЛЕЙ:")
    for name, example in unique_fields.items():
        print(f"- {name}: {example}")

Всего ссылок в файле: 39561. Проверим первые 20.
Заходим [1/20]: https://www.cian.ru/sale/flat/324994191/
    Новое поле: 'Тип жилья' (Пример: Вторичка / Апартаменты)
    Новое поле: 'Общая площадь' (Пример: 16 м²)
    Новое поле: 'Жилая площадь' (Пример: 10 м²)
    Новое поле: 'Площадь кухни' (Пример: 5 м²)
    Новое поле: 'Высота потолков' (Пример: 2,7 м)
    Новое поле: 'Санузел' (Пример: 1 раздельный)
    Новое поле: 'Вид из окон' (Пример: Во двор)
    Новое поле: 'Ремонт' (Пример: Евроремонт)
    Новое поле: 'Продаётся с мебелью' (Пример: Да)
    Новое поле: 'Тип дома' (Пример: Кирпичный)
    Новое поле: 'Несовершеннолетние собственники' (Пример: Нет)
    Новое поле: 'Материнский капитал при покупке' (Пример: Не использовался)
Заходим [2/20]: https://www.cian.ru/sale/flat/320317503/
    Новое поле: 'Парковка' (Пример: Наземная)
Заходим [3/20]: https://www.cian.ru/sale/flat/322151830/
Заходим [4/20]: https://www.cian.ru/sale/flat/324172390/
Заходим [5/20]: https://www.cian.ru/sale/flat/323600775/
    Новое поле: 'Год постройки' (Пример: 1978)
    Новое поле: 'Строительная серия' (Пример: Индивидуальный проект)
    Новое поле: 'Тип перекрытий' (Пример: Железобетонные)
    Новое поле: 'Подъезды' (Пример: 4)
    Новое поле: 'Отопление' (Пример: Центральное)
    Новое поле: 'Аварийность' (Пример: Нет)
    Новое поле: 'Газоснабжение' (Пример: Центральное)
Заходим [6/20]: https://www.cian.ru/sale/flat/323201527/
    Новое поле: 'Балкон/лоджия' (Пример: 1 лоджия)
Заходим [7/20]: https://www.cian.ru/sale/flat/323240964/
Заходим [8/20]: https://www.cian.ru/sale/flat/324212999/
Заходим [9/20]: https://www.cian.ru/sale/flat/309052464/
    Новое поле: 'Количество лифтов' (Пример: 1 пассажирский)
    Новое поле: 'О подъезде' (Пример: Есть мусоропровод)
Заходим [10/20]: https://www.cian.ru/sale/flat/321742295/
Заходим [11/20]: https://www.cian.ru/sale/flat/322890214/
Заходим [12/20]: https://www.cian.ru/sale/flat/321548974/
Заходим [13/20]: https://www.cian.ru/sale/flat/320856850/
Заходим [14/20]: https://www.cian.ru/sale/flat/323201520/
Заходим [15/20]: https://www.cian.ru/sale/flat/324689269/
Заходим [16/20]: https://www.cian.ru/sale/flat/320006993/
Заходим [17/20]: https://www.cian.ru/sale/flat/323815180/
Заходим [18/20]: https://www.cian.ru/sale/flat/324178128/
Заходим [19/20]: https://www.cian.ru/sale/flat/324403220/
Заходим [20/20]: https://www.cian.ru/sale/flat/322349698/

========================================
ИТОГОВЫЙ СПИСОК ДОСТУПНЫХ ПОЛЕЙ:
- Тип жилья: Вторичка / Апартаменты
- Общая площадь: 16 м²
- Жилая площадь: 10 м²
- Площадь кухни: 5 м²
- Высота потолков: 2,7 м
- Санузел: 1 раздельный
- Вид из окон: Во двор
- Ремонт: Евроремонт
- Продаётся с мебелью: Да
- Тип дома: Кирпичный
- Несовершеннолетние собственники: Нет
- Материнский капитал при покупке: Не использовался
- Парковка: Наземная
- Год постройки: 1978
- Строительная серия: Индивидуальный проект
- Тип перекрытий: Железобетонные
- Подъезды: 4
- Отопление: Центральное
- Аварийность: Нет
- Газоснабжение: Центральное
- Балкон/лоджия: 1 лоджия
- Количество лифтов: 1 пассажирский
- О подъезде: Есть мусоропровод

In [73]:
#этот кусок работает только с впн, иначе гугл блочит запрос
from googletrans import Translator

#создаем здесь себе список доступных атрибутов, заодно перееводим все на англ для названия полей
translator = Translator()

keys_list = list(unique_fields.keys())
values_list = list(unique_fields.values())

attributes = pd.DataFrame(zip(keys_list, 
                              [translator.translate(name, dest='en').text.lower().replace(' ', '_').replace('/','_') for name in keys_list],
                              values_list),
                          columns = ['field_name_ru', 'field_name_en', 'field_example'])
attributes

,field_name_ru,field_name_en,field_example
0,Тип жилья,housing_type,Вторичка / Апартаменты
1,Общая площадь,total_area,16 м²
2,Жилая площадь,living_area,10 м²
3,Площадь кухни,kitchen_area,5 м²
4,Высота потолков,ceiling_height,"2,7 м"
5,Санузел,bathroom,1 раздельный
6,Вид из окон,view_from_the_windows,Во двор
7,Ремонт,repair,Евроремонт
8,Продаётся с мебелью,sold_with_furniture,Да
9,Тип дома,home_type,Кирпичный
10,Несовершеннолетние собственники,minor_owners,Нет
11,Материнский капитал при покупке,maternity_capital_upon_purchase,Не использовался
12,Парковка,parking,Наземная
13,Год постройки,year_of_construction,1978
14,Строительная серия,construction_series,Индивидуальный проект
15,Тип перекрытий,floor_type,Железобетонные
16,Подъезды,entrances,4
17,Отопление,heating,Центральное
18,Аварийность,accident_rate,Нет
19,Газоснабжение,gas_supply,Центральное
20,Балкон/лоджия,balcony_loggia,1 лоджия
21,Количество лифтов,number_of_elevators,1 пассажирский
22,О подъезде,about_the_entrance,Есть мусоропровод

### Проходимся по каждому объявлению и вытаскиваем характеристики

In [144]:
import time
import pandas as pd
import re
import random
import json
import dateparser
import requests

from datetime import datetime
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup

#-------------БЛОК ФУНКЦИЙ------------------------
#ищем координаты объекта
def get_coords_from_script(soup):
    scripts = soup.find_all('script')
    for script in scripts:
        if script.string:
            #ищем подстроку "coordinates":{"lat":55.123,"lng":37.123} - ищем все такие куски
            matches = re.findall(r'"coordinates":\{"lat":([\d\.]+),"lng":([\d\.]+)\}', script.string)
            for lat, lng in matches:
                #если нули, то ничего не возвращаем
                if float(lat) != 0 and float(lng) != 0:
                    return float(lat), float(lng)
    return None, None

#ищем ссылки и сохраняем их в нормальном формте
def get_photos_from_script(soup):
    scripts = soup.find_all('script')
    found_urls = []
    for script in scripts:
        if script.string and '"photos":[' in script.string:
            urls = re.findall(r'"fullUrl":"([^"]+)"', script.string)
            clean_urls = [u.replace("\\u002F", "/") for u in urls]
            found_urls.extend(clean_urls)
    
    return list(set(found_urls))

#строка с циана'вчера, 18:55' или '25 окт, 14:00' превращается в нормальный datetime
def parse_date_string(date_str):

    clean_str = str(date_str).replace("Обновлено", "").replace(":", "", 1).strip()
    
    try:
        dt = dateparser.parse(clean_str, languages=['ru'])
        
        if dt:
            return dt.strftime("%Y-%m-%d %H:%M:%S")
        else:
            return date_str
            
    except Exception:
        return date_str


def send_telegram_alert(message):
    #телега
    try:
        url = f"https://api.telegram.org/bot{TG_TOKEN}/sendMessage"
        data = {"chat_id": TG_CHAT_ID, "text": message}
        requests.post(url, data=data)
    except Exception as e:
        print(f"Не удалось отправить уведомление: {e}")


#-----Работа в файлах-----------
INPUT_FILE = "cian_urls_wo_duplicates.csv" #файл со ссылками
OUTPUT_FILE = "cian_extended_data.csv" #файл с расширенными данными

TG_TOKEN = "8323989130:AAG3ezUom-z5heFqH3Fms1wwA9K_HguLaEI"  
TG_CHAT_ID = 389535583

#если файла с данными нет, то создаем его на основе файла со ссылками
#если расширенный файл уже создан, то дополняем только то, что не заполнилось в предыдущие запуски
if os.path.exists(OUTPUT_FILE):
    print(f"Найден существующий файл {OUTPUT_FILE}.")
    df = pd.read_csv(OUTPUT_FILE, low_memory=False)
else:
    print(f"Файл {OUTPUT_FILE} не найден. Создаем новый на основе {INPUT_FILE}.")
    try:
        df = pd.read_csv(INPUT_FILE, low_memory=False)
    except FileNotFoundError:
        print(f"ОШИБКА: Исходный файл {INPUT_FILE} не найден!")
        exit()



#настройки браузера
options = webdriver.ChromeOptions()
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument("--log-level=3")
options.page_load_strategy = 'eager'

#пытаемся обойти блокировку vpn (это не сработало)
options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

prefs = {"profile.managed_default_content_settings.images": 2}
options.add_experimental_option("prefs", prefs)


driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
print("Браузер запущен")

#df = df.loc[[1677]]
#функция для поиска атрибутов в блоке OfferSummaryInfoItem
def get_cian_attribute(soup, label_text):
    all_items = soup.find_all('div', {'data-name': 'OfferSummaryInfoItem'})
    for item in all_items:
        texts = item.find_all('p')
        if len(texts) >= 2:
            #ищем названия полей + чистим от всяких нечитаемых символов
            name_raw = texts[0].get_text(strip=True)
            name_clean = " ".join(name_raw.split()) #"О\xa0подъезде"
            
            value_raw = texts[1].get_text(strip=True)
            value_clean = " ".join(value_raw.split())

        
            if label_text.lower() in name_clean.lower():
                return value_clean
    return None


#итоговый список колонок, полученный с помощью скриптов выше
new_cols = [
    'title', 'rooms_count',
    'housing_type', 'total_area', 'living_area', 'kitchen_area', 'floor_info', 
    'ceiling_height', 'bathroom', 'balcony_loggia', 'view_from_the_windows', 
    'repair', 'year_of_construction', 'construction_series', 'number_of_elevators', 
    'floor_type', 'entrances', 'about_the_entrance', 'parking', 'heating', 
    'accident_rate', 'gas_supply', 'sold_with_furniture', 'home_type', 
    'metro_info', 'highway_info', 'description', 'lat', 'lng', 
    'minor_owners', 'maternity_capital', 
    'publication_date_str', 'publication_date', 'photos_url', 'request_time'
]


for col in new_cols:
    if col not in df.columns:
        df[col] = None

#--------ОСНОВА-----
try:
    #сколько осталось обработать
    total_rows = len(df)
    #индексы строк, которые надо обработать впервые или заново, если возникла ошибка с ВПН
    rows_to_process = df[(df['request_time'].isna()) | (df['title']=='Кажется, у вас включён VPN') | (df['title'].isna())].index.tolist()
    
    print(f"\nВсего строк: {total_rows}, обработать осталось  {len(rows_to_process)}")

    for i, index in enumerate(rows_to_process):
        start_time = time.time()
        
        row = df.loc[index]
        url = row['url']
        address = row['address']
        
        if pd.isna(url) or "cian.ru" not in str(url):
            continue
            
        print(f"[Обработка {i+1}/{len(rows_to_process)}] (номер строки в файле – {index+1})")
        
        try:
            driver.get(url)
            #проставляем дату
            current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            '''
            #на случай капчи
            while True:
                page_title = driver.title.lower()
                #смотрим на заголовок страницы
                if "captcha" in page_title or "security" in page_title or "доступ ограничен" in driver.page_source:
                    print(f"!!! КАПЧА ОБНАРУЖЕНА !!! Скрипт на паузе.")
                    #вызывааем звук, если капча
                    try:
                        import winsound
                        winsound.Beep(1000, 500) 
                    except:
                        pass
                    time.sleep(10) #ждет 10 сек и вызывает проверку снова
                else:
                    #выходим, если все ок и капчи нет
                    break
            '''


            #задаем рандомное время прогрузки страницы, чтобы больше быть похожим на человека
            #sleep_time = random.uniform(1.5, 2.5)
            #time.sleep(sleep_time) 
    
            soup = BeautifulSoup(driver.page_source, 'html.parser')
            
            #записываем название объявления и определяем комнатность
            h1_tag = soup.find('h1')
            title_text = h1_tag.get_text(strip=True) if h1_tag else "Не найден"

            sent_alert = False # Флаг, чтобы не спамить сообщениями каждую секунду
            
            while True:
                
                # Если сработала защита
                if "VPN" in title_text.upper() or "captcha" in title_text.lower():                    
                    # === ОТПРАВЛЯЕМ УВЕДОМЛЕНИЕ (Один раз) ===
                    if not sent_alert:
                        send_telegram_alert("🚨 Циан выдал КАПЧУ или ошибку VPN. Скрипт на паузе!")
                        sent_alert = True
                        
                    time.sleep(10)
                else:
                    if sent_alert:
                        send_telegram_alert("✅ Капча пройдена, работаю дальше.")
                    break
            
            rooms_count = None
            if h1_tag:
                #ищем цифру перед "-комн"
                rooms_match = re.search(r'(\d+)-комн', title_text, re.IGNORECASE)
                if rooms_match:
                    rooms_count = rooms_match.group(1)
                #студия
                elif "студия" in title_text.lower():
                    rooms_count = "Студия"
                #свободная планировка
                elif "свобод" in title_text.lower() and "планиров" in title_text.lower():
                    rooms_count = "Своб. планировка"
                    
            #собираем все атрибуты
            housing_type = get_cian_attribute(soup, "Тип жилья")
            total_area = get_cian_attribute(soup, "Общая площадь") or get_cian_attribute(soup, "Общая")
            living_area = get_cian_attribute(soup, "Жилая площадь")
            kitchen_area = get_cian_attribute(soup, "Площадь кухни")
            ceiling_height = get_cian_attribute(soup, "Высота потолков")
            bathroom = get_cian_attribute(soup, "Санузел")
            balcony_loggia = get_cian_attribute(soup, "Балкон/лоджия")
            view_from_the_windows = get_cian_attribute(soup, "Вид из окон")
            repair = get_cian_attribute(soup, "Ремонт")
            sold_with_furniture = get_cian_attribute(soup, "Продаётся с мебелью")
            year_of_construction = get_cian_attribute(soup, "Год постройки") or get_cian_attribute(soup, "Срок сдачи")
            construction_series = get_cian_attribute(soup, "Строительная серия")
            number_of_elevators = get_cian_attribute(soup, "Количество лифтов")
            floor_type = get_cian_attribute(soup, "Тип перекрытий")
            entrances = get_cian_attribute(soup, "Подъезды")
            about_the_entrance = get_cian_attribute(soup, "О подъезде")
            parking = get_cian_attribute(soup, "Парковка")
            heating = get_cian_attribute(soup, "Отопление")
            accident_rate = get_cian_attribute(soup, "Аварийность")
            gas_supply = get_cian_attribute(soup, "Газоснабжение")
            home_type = get_cian_attribute(soup, "Тип дома")
            minor_owners = get_cian_attribute(soup, "Несовершеннолетние собственники")
            maternity_capital = get_cian_attribute(soup, "Материнский капитал при покупке")

            #определям этаж
            floor_info = get_cian_attribute(soup, "Этаж") 
            if not floor_info:
                try:
                    floor_labels = soup.find_all(string=re.compile(r"^Этаж$"))
                    for label in floor_labels:
                        parent = label.parent
                        next_elem = parent.find_next_sibling()
                        if next_elem:
                            text_val = next_elem.get_text(strip=True)
                            if re.search(r'\d', text_val):
                                floor_info = text_val
                                break
                except:
                    pass
            if not floor_info:
                h1_tag = soup.find('h1')
                if h1_tag:
                    floor_regex = re.search(r'(\d+)\s*(?:/|из)\s*(\d+)', h1_tag.get_text())
                    if floor_regex:
                        floor_info = f"{floor_regex.group(1)} из {floor_regex.group(2)}"
            if not floor_info: floor_info = "Не найден"

            #метро и описание
            metro_block = soup.find('ul', {'data-name': 'UndergroundList'})
            metro_info = None
            
            if metro_block:
                metro_items = []
                #перебираем каждый пункт метро отдельно (теги <li>)
                for item in metro_block.find_all('li'):
                    #чистый текст: "Автозаводская 5 мин."
                    text = item.get_text(strip=True, separator=" ")
                    
                    #превращаем весь HTML пункта в строку и ищем ключевые слова в названиях классов/иконок
                    item_html = str(item).lower()
                    
                    #ищем иконку машины
                    if "m14 7-.84" in item_html:
                        transport_type = "на машине"
                    #по умолчанию пешком
                    else:
                        transport_type = "пешком"
                        
                    #сбираем обратно в строку
                    if "Посмотреть ещё" in text:
                        continue
                    metro_items.append(f"{text} ({transport_type})")
                
                #все объединяем
                metro_info = ", ".join(metro_items)

            #highway
            highway_block = soup.find('ul', {'data-name': 'HighwayList'})
            highway_info = highway_block.get_text(separator=", ", strip=True) if highway_block else None

            
            desc_block = soup.find('div', {'data-name': 'Description'})
            description = desc_block.get_text(separator=" ", strip=True) if desc_block else None

            #дата публикации объявления по фразе "Обновлено"
            pub_date_str = "Не найдена"
            date_node = soup.find(string=re.compile(r"Обновлено"))
            if date_node:
                pub_date_str = date_node.strip()

            pub_date = parse_date_string(pub_date_str)
            
            #вытаскиваем первые 15 ссылок на фотки
            raw_photos = get_photos_from_script(soup)
            photos_str = ", ".join(raw_photos[:15])

            #координаты
            lat, lng = get_coords_from_script(soup)

            #записываем все полчившеееся
            df.at[index, 'title'] = title_text
            df.at[index, 'rooms_count'] = rooms_count
            
            df.at[index, 'housing_type'] = housing_type
            df.at[index, 'total_area'] = total_area
            df.at[index, 'living_area'] = living_area
            df.at[index, 'kitchen_area'] = kitchen_area
            df.at[index, 'floor_info'] = floor_info 
            df.at[index, 'ceiling_height'] = ceiling_height
            df.at[index, 'bathroom'] = bathroom
            df.at[index, 'balcony_loggia'] = balcony_loggia
            df.at[index, 'view_from_the_windows'] = view_from_the_windows
            df.at[index, 'repair'] = repair
            df.at[index, 'year_of_construction'] = year_of_construction
            df.at[index, 'construction_series'] = construction_series
            df.at[index, 'number_of_elevators'] = number_of_elevators
            df.at[index, 'floor_type'] = floor_type
            df.at[index, 'entrances'] = entrances
            df.at[index, 'about_the_entrance'] = about_the_entrance
            df.at[index, 'parking'] = parking
            df.at[index, 'heating'] = heating
            df.at[index, 'accident_rate'] = accident_rate
            df.at[index, 'gas_supply'] = gas_supply
            df.at[index, 'sold_with_furniture'] = sold_with_furniture
            df.at[index, 'home_type'] = home_type
            df.at[index, 'minor_owners'] = minor_owners
            df.at[index, 'maternity_capital'] = maternity_capital

            
            df.at[index, 'metro_info'] = metro_info
            df.at[index, 'highway_info'] = highway_info
            
            df.at[index, 'description'] = description
            df.at[index, 'lat'] = lat
            df.at[index, 'lng'] = lng
            df.at[index, 'publication_date_str'] = pub_date_str
            df.at[index, 'publication_date'] = pub_date
            df.at[index, 'photos_url'] = photos_str
            df.at[index, 'request_time'] = current_time

            
            end_time = time.time()
            execution_time = end_time - start_time
            print(f"--> Время обработки объявления: {execution_time:.2f} сек.")
            
            df.at[index, 'process_time'] = round(execution_time, 2)

            #сохраняем инфу каждые 5 объявлений, чтобы иметь возможность перезапустить скрипт при ошибке
            if (i + 1) % 5 == 0:
                df.to_csv(OUTPUT_FILE, index=False, encoding='utf-8-sig')
                print(f"   [Сохранено {i+1} строк]")


        except Exception as e:
            print(f"Ошибка: {e}")
            continue

finally:
    driver.quit()
    df.to_csv(OUTPUT_FILE, index=False, encoding='utf-8-sig')
    print(f"\nГОТОВО! Сохранено в {OUTPUT_FILE}")

Найден существующий файл cian_extended_data.csv.
Браузер запущен

Всего строк: 38700, обработать осталось  418
[Обработка 1/418] (номер строки в файле – 35516)
--> Время обработки объявления: 2.45 сек.
[Обработка 2/418] (номер строки в файле – 35531)

C:\Users\munir\AppData\Local\Temp\ipykernel_18720\195610640.py:343: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2009' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[index, 'year_of_construction'] = year_of_construction
C:\Users\munir\AppData\Local\Temp\ipykernel_18720\195610640.py:347: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[index, 'entrances'] = entrances

--> Время обработки объявления: 1.21 сек.
[Обработка 3/418] (номер строки в файле – 35601)
--> Время обработки объявления: 0.80 сек.
[Обработка 4/418] (номер строки в файле – 35602)
--> Время обработки объявления: 0.71 сек.
[Обработка 5/418] (номер строки в файле – 35603)
--> Время обработки объявления: 0.82 сек.
   [Сохранено 5 строк]
[Обработка 6/418] (номер строки в файле – 35604)
--> Время обработки объявления: 1.08 сек.
[Обработка 7/418] (номер строки в файле – 35621)
--> Время обработки объявления: 0.85 сек.
[Обработка 8/418] (номер строки в файле – 35641)
--> Время обработки объявления: 0.71 сек.
[Обработка 9/418] (номер строки в файле – 35642)
--> Время обработки объявления: 0.76 сек.
[Обработка 10/418] (номер строки в файле – 35643)
--> Время обработки объявления: 0.85 сек.
   [Сохранено 10 строк]
[Обработка 11/418] (номер строки в файле – 35644)
--> Время обработки объявления: 0.96 сек.
[Обработка 12/418] (номер строки в файле – 35645)
--> Время обработки объявления: 0.93 сек.
[Обработка 13/418] (номер строки в файле – 35646)
--> Время обработки объявления: 0.77 сек.
[Обработка 14/418] (номер строки в файле – 38296)
--> Время обработки объявления: 0.74 сек.
[Обработка 15/418] (номер строки в файле – 38297)
--> Время обработки объявления: 0.82 сек.
   [Сохранено 15 строк]
[Обработка 16/418] (номер строки в файле – 38298)
--> Время обработки объявления: 0.92 сек.
[Обработка 17/418] (номер строки в файле – 38299)
--> Время обработки объявления: 0.75 сек.
[Обработка 18/418] (номер строки в файле – 38300)
--> Время обработки объявления: 0.78 сек.
[Обработка 19/418] (номер строки в файле – 38301)
--> Время обработки объявления: 0.69 сек.
[Обработка 20/418] (номер строки в файле – 38302)
--> Время обработки объявления: 0.79 сек.
   [Сохранено 20 строк]
[Обработка 21/418] (номер строки в файле – 38303)
--> Время обработки объявления: 1.10 сек.
[Обработка 22/418] (номер строки в файле – 38304)
--> Время обработки объявления: 0.79 сек.
[Обработка 23/418] (номер строки в файле – 38305)
--> Время обработки объявления: 0.82 сек.
[Обработка 24/418] (номер строки в файле – 38306)
--> Время обработки объявления: 0.72 сек.
[Обработка 25/418] (номер строки в файле – 38307)
--> Время обработки объявления: 0.81 сек.
   [Сохранено 25 строк]
[Обработка 26/418] (номер строки в файле – 38308)
--> Время обработки объявления: 1.00 сек.
[Обработка 27/418] (номер строки в файле – 38309)
--> Время обработки объявления: 0.84 сек.
[Обработка 28/418] (номер строки в файле – 38310)
--> Время обработки объявления: 0.87 сек.
[Обработка 29/418] (номер строки в файле – 38311)
--> Время обработки объявления: 0.79 сек.
[Обработка 30/418] (номер строки в файле – 38312)
--> Время обработки объявления: 0.93 сек.
   [Сохранено 30 строк]
[Обработка 31/418] (номер строки в файле – 38313)
--> Время обработки объявления: 0.90 сек.
[Обработка 32/418] (номер строки в файле – 38314)
--> Время обработки объявления: 0.80 сек.
[Обработка 33/418] (номер строки в файле – 38315)
--> Время обработки объявления: 1.06 сек.
[Обработка 34/418] (номер строки в файле – 38316)
--> Время обработки объявления: 0.81 сек.
[Обработка 35/418] (номер строки в файле – 38317)
--> Время обработки объявления: 0.83 сек.
   [Сохранено 35 строк]
[Обработка 36/418] (номер строки в файле – 38318)
--> Время обработки объявления: 1.07 сек.
[Обработка 37/418] (номер строки в файле – 38319)
--> Время обработки объявления: 0.76 сек.
[Обработка 38/418] (номер строки в файле – 38320)
--> Время обработки объявления: 0.80 сек.
[Обработка 39/418] (номер строки в файле – 38321)
--> Время обработки объявления: 0.79 сек.
[Обработка 40/418] (номер строки в файле – 38322)
--> Время обработки объявления: 0.77 сек.
   [Сохранено 40 строк]
[Обработка 41/418] (номер строки в файле – 38323)
--> Время обработки объявления: 1.10 сек.
[Обработка 42/418] (номер строки в файле – 38324)
--> Время обработки объявления: 1.00 сек.
[Обработка 43/418] (номер строки в файле – 38325)
--> Время обработки объявления: 1.87 сек.
[Обработка 44/418] (номер строки в файле – 38326)
--> Время обработки объявления: 0.71 сек.
[Обработка 45/418] (номер строки в файле – 38327)
--> Время обработки объявления: 0.80 сек.
   [Сохранено 45 строк]
[Обработка 46/418] (номер строки в файле – 38328)
--> Время обработки объявления: 1.21 сек.
[Обработка 47/418] (номер строки в файле – 38329)
--> Время обработки объявления: 0.78 сек.
[Обработка 48/418] (номер строки в файле – 38330)
--> Время обработки объявления: 0.83 сек.
[Обработка 49/418] (номер строки в файле – 38331)
--> Время обработки объявления: 1.02 сек.
[Обработка 50/418] (номер строки в файле – 38332)
--> Время обработки объявления: 0.83 сек.
   [Сохранено 50 строк]
[Обработка 51/418] (номер строки в файле – 38333)
--> Время обработки объявления: 1.01 сек.
[Обработка 52/418] (номер строки в файле – 38334)
--> Время обработки объявления: 0.85 сек.
[Обработка 53/418] (номер строки в файле – 38335)
--> Время обработки объявления: 0.80 сек.
[Обработка 54/418] (номер строки в файле – 38336)
--> Время обработки объявления: 0.80 сек.
[Обработка 55/418] (номер строки в файле – 38337)
--> Время обработки объявления: 0.73 сек.
   [Сохранено 55 строк]
[Обработка 56/418] (номер строки в файле – 38338)
--> Время обработки объявления: 0.93 сек.
[Обработка 57/418] (номер строки в файле – 38339)
--> Время обработки объявления: 0.79 сек.
[Обработка 58/418] (номер строки в файле – 38340)
--> Время обработки объявления: 0.76 сек.
[Обработка 59/418] (номер строки в файле – 38341)
--> Время обработки объявления: 0.75 сек.
[Обработка 60/418] (номер строки в файле – 38342)
--> Время обработки объявления: 0.79 сек.
   [Сохранено 60 строк]
[Обработка 61/418] (номер строки в файле – 38343)
--> Время обработки объявления: 0.90 сек.
[Обработка 62/418] (номер строки в файле – 38344)
--> Время обработки объявления: 0.82 сек.
[Обработка 63/418] (номер строки в файле – 38345)
--> Время обработки объявления: 0.85 сек.
[Обработка 64/418] (номер строки в файле – 38346)
--> Время обработки объявления: 0.85 сек.
[Обработка 65/418] (номер строки в файле – 38347)
--> Время обработки объявления: 0.82 сек.
   [Сохранено 65 строк]
[Обработка 66/418] (номер строки в файле – 38348)
--> Время обработки объявления: 0.94 сек.
[Обработка 67/418] (номер строки в файле – 38349)
--> Время обработки объявления: 0.78 сек.
[Обработка 68/418] (номер строки в файле – 38350)
--> Время обработки объявления: 0.74 сек.
[Обработка 69/418] (номер строки в файле – 38351)
--> Время обработки объявления: 0.68 сек.
[Обработка 70/418] (номер строки в файле – 38352)
--> Время обработки объявления: 0.79 сек.
   [Сохранено 70 строк]
[Обработка 71/418] (номер строки в файле – 38353)
--> Время обработки объявления: 0.94 сек.
[Обработка 72/418] (номер строки в файле – 38354)
--> Время обработки объявления: 0.81 сек.
[Обработка 73/418] (номер строки в файле – 38355)
--> Время обработки объявления: 0.77 сек.
[Обработка 74/418] (номер строки в файле – 38356)
--> Время обработки объявления: 0.81 сек.
[Обработка 75/418] (номер строки в файле – 38357)
--> Время обработки объявления: 0.77 сек.
   [Сохранено 75 строк]
[Обработка 76/418] (номер строки в файле – 38358)
--> Время обработки объявления: 0.94 сек.
[Обработка 77/418] (номер строки в файле – 38359)
--> Время обработки объявления: 0.76 сек.
[Обработка 78/418] (номер строки в файле – 38360)
--> Время обработки объявления: 0.83 сек.
[Обработка 79/418] (номер строки в файле – 38361)
--> Время обработки объявления: 0.74 сек.
[Обработка 80/418] (номер строки в файле – 38362)
--> Время обработки объявления: 0.69 сек.
   [Сохранено 80 строк]
[Обработка 81/418] (номер строки в файле – 38363)
--> Время обработки объявления: 1.06 сек.
[Обработка 82/418] (номер строки в файле – 38364)
--> Время обработки объявления: 0.81 сек.
[Обработка 83/418] (номер строки в файле – 38365)
--> Время обработки объявления: 0.75 сек.
[Обработка 84/418] (номер строки в файле – 38366)
--> Время обработки объявления: 0.73 сек.
[Обработка 85/418] (номер строки в файле – 38367)
--> Время обработки объявления: 1.26 сек.
   [Сохранено 85 строк]
[Обработка 86/418] (номер строки в файле – 38368)
--> Время обработки объявления: 1.06 сек.
[Обработка 87/418] (номер строки в файле – 38369)
--> Время обработки объявления: 1.05 сек.
[Обработка 88/418] (номер строки в файле – 38370)
--> Время обработки объявления: 0.92 сек.
[Обработка 89/418] (номер строки в файле – 38371)
--> Время обработки объявления: 0.83 сек.
[Обработка 90/418] (номер строки в файле – 38372)
--> Время обработки объявления: 0.90 сек.
   [Сохранено 90 строк]
[Обработка 91/418] (номер строки в файле – 38373)
--> Время обработки объявления: 0.94 сек.
[Обработка 92/418] (номер строки в файле – 38374)
--> Время обработки объявления: 0.79 сек.
[Обработка 93/418] (номер строки в файле – 38375)
--> Время обработки объявления: 0.71 сек.
[Обработка 94/418] (номер строки в файле – 38376)
--> Время обработки объявления: 0.81 сек.
[Обработка 95/418] (номер строки в файле – 38377)
--> Время обработки объявления: 0.85 сек.
   [Сохранено 95 строк]
[Обработка 96/418] (номер строки в файле – 38378)
--> Время обработки объявления: 1.19 сек.
[Обработка 97/418] (номер строки в файле – 38379)
--> Время обработки объявления: 0.83 сек.
[Обработка 98/418] (номер строки в файле – 38380)
--> Время обработки объявления: 0.80 сек.
[Обработка 99/418] (номер строки в файле – 38381)
--> Время обработки объявления: 0.95 сек.
[Обработка 100/418] (номер строки в файле – 38382)
--> Время обработки объявления: 0.78 сек.
   [Сохранено 100 строк]
[Обработка 101/418] (номер строки в файле – 38383)
--> Время обработки объявления: 0.97 сек.
[Обработка 102/418] (номер строки в файле – 38384)
--> Время обработки объявления: 0.80 сек.
[Обработка 103/418] (номер строки в файле – 38385)
--> Время обработки объявления: 0.76 сек.
[Обработка 104/418] (номер строки в файле – 38386)
--> Время обработки объявления: 0.82 сек.
[Обработка 105/418] (номер строки в файле – 38387)
--> Время обработки объявления: 0.88 сек.
   [Сохранено 105 строк]
[Обработка 106/418] (номер строки в файле – 38388)
--> Время обработки объявления: 1.18 сек.
[Обработка 107/418] (номер строки в файле – 38389)
--> Время обработки объявления: 0.74 сек.
[Обработка 108/418] (номер строки в файле – 38390)
--> Время обработки объявления: 0.87 сек.
[Обработка 109/418] (номер строки в файле – 38391)
--> Время обработки объявления: 0.83 сек.
[Обработка 110/418] (номер строки в файле – 38392)
--> Время обработки объявления: 0.79 сек.
   [Сохранено 110 строк]
[Обработка 111/418] (номер строки в файле – 38393)
--> Время обработки объявления: 1.01 сек.
[Обработка 112/418] (номер строки в файле – 38394)
--> Время обработки объявления: 0.77 сек.
[Обработка 113/418] (номер строки в файле – 38395)
--> Время обработки объявления: 0.80 сек.
[Обработка 114/418] (номер строки в файле – 38396)
--> Время обработки объявления: 0.77 сек.
[Обработка 115/418] (номер строки в файле – 38397)
--> Время обработки объявления: 1.21 сек.
   [Сохранено 115 строк]
[Обработка 116/418] (номер строки в файле – 38398)
--> Время обработки объявления: 1.09 сек.
[Обработка 117/418] (номер строки в файле – 38399)
--> Время обработки объявления: 0.97 сек.
[Обработка 118/418] (номер строки в файле – 38400)
--> Время обработки объявления: 0.85 сек.
[Обработка 119/418] (номер строки в файле – 38401)
--> Время обработки объявления: 0.81 сек.
[Обработка 120/418] (номер строки в файле – 38402)
--> Время обработки объявления: 0.84 сек.
   [Сохранено 120 строк]
[Обработка 121/418] (номер строки в файле – 38403)
--> Время обработки объявления: 1.05 сек.
[Обработка 122/418] (номер строки в файле – 38404)
--> Время обработки объявления: 0.75 сек.
[Обработка 123/418] (номер строки в файле – 38405)
--> Время обработки объявления: 0.75 сек.
[Обработка 124/418] (номер строки в файле – 38406)
--> Время обработки объявления: 0.79 сек.
[Обработка 125/418] (номер строки в файле – 38407)
--> Время обработки объявления: 0.70 сек.
   [Сохранено 125 строк]
[Обработка 126/418] (номер строки в файле – 38408)
--> Время обработки объявления: 1.02 сек.
[Обработка 127/418] (номер строки в файле – 38409)
--> Время обработки объявления: 0.76 сек.
[Обработка 128/418] (номер строки в файле – 38410)
--> Время обработки объявления: 0.73 сек.
[Обработка 129/418] (номер строки в файле – 38411)
--> Время обработки объявления: 0.74 сек.
[Обработка 130/418] (номер строки в файле – 38412)
--> Время обработки объявления: 0.77 сек.
   [Сохранено 130 строк]
[Обработка 131/418] (номер строки в файле – 38413)
--> Время обработки объявления: 0.90 сек.
[Обработка 132/418] (номер строки в файле – 38414)
--> Время обработки объявления: 0.75 сек.
[Обработка 133/418] (номер строки в файле – 38415)
--> Время обработки объявления: 0.83 сек.
[Обработка 134/418] (номер строки в файле – 38416)
--> Время обработки объявления: 0.92 сек.
[Обработка 135/418] (номер строки в файле – 38417)
--> Время обработки объявления: 1.12 сек.
   [Сохранено 135 строк]
[Обработка 136/418] (номер строки в файле – 38418)
--> Время обработки объявления: 0.82 сек.
[Обработка 137/418] (номер строки в файле – 38419)
--> Время обработки объявления: 0.85 сек.
[Обработка 138/418] (номер строки в файле – 38420)
--> Время обработки объявления: 0.82 сек.
[Обработка 139/418] (номер строки в файле – 38421)
--> Время обработки объявления: 0.75 сек.
[Обработка 140/418] (номер строки в файле – 38422)
--> Время обработки объявления: 1.77 сек.
   [Сохранено 140 строк]
[Обработка 141/418] (номер строки в файле – 38423)
--> Время обработки объявления: 1.11 сек.
[Обработка 142/418] (номер строки в файле – 38424)
--> Время обработки объявления: 0.78 сек.
[Обработка 143/418] (номер строки в файле – 38425)
--> Время обработки объявления: 0.81 сек.
[Обработка 144/418] (номер строки в файле – 38426)
--> Время обработки объявления: 1.01 сек.
[Обработка 145/418] (номер строки в файле – 38427)
--> Время обработки объявления: 0.86 сек.
   [Сохранено 145 строк]
[Обработка 146/418] (номер строки в файле – 38428)
--> Время обработки объявления: 0.87 сек.
[Обработка 147/418] (номер строки в файле – 38429)
--> Время обработки объявления: 0.85 сек.
[Обработка 148/418] (номер строки в файле – 38430)
--> Время обработки объявления: 1.00 сек.
[Обработка 149/418] (номер строки в файле – 38431)
--> Время обработки объявления: 0.97 сек.
[Обработка 150/418] (номер строки в файле – 38432)
--> Время обработки объявления: 0.74 сек.
   [Сохранено 150 строк]
[Обработка 151/418] (номер строки в файле – 38433)
--> Время обработки объявления: 1.13 сек.
[Обработка 152/418] (номер строки в файле – 38434)
--> Время обработки объявления: 0.80 сек.
[Обработка 153/418] (номер строки в файле – 38435)
--> Время обработки объявления: 1.00 сек.
[Обработка 154/418] (номер строки в файле – 38436)
--> Время обработки объявления: 1.01 сек.
[Обработка 155/418] (номер строки в файле – 38437)
--> Время обработки объявления: 0.71 сек.
   [Сохранено 155 строк]
[Обработка 156/418] (номер строки в файле – 38438)
--> Время обработки объявления: 1.00 сек.
[Обработка 157/418] (номер строки в файле – 38439)
--> Время обработки объявления: 1.04 сек.
[Обработка 158/418] (номер строки в файле – 38440)
--> Время обработки объявления: 0.80 сек.
[Обработка 159/418] (номер строки в файле – 38441)
--> Время обработки объявления: 0.82 сек.
[Обработка 160/418] (номер строки в файле – 38442)
--> Время обработки объявления: 0.83 сек.
   [Сохранено 160 строк]
[Обработка 161/418] (номер строки в файле – 38443)
--> Время обработки объявления: 1.05 сек.
[Обработка 162/418] (номер строки в файле – 38444)
--> Время обработки объявления: 0.83 сек.
[Обработка 163/418] (номер строки в файле – 38445)
--> Время обработки объявления: 0.83 сек.
[Обработка 164/418] (номер строки в файле – 38446)
--> Время обработки объявления: 0.99 сек.
[Обработка 165/418] (номер строки в файле – 38447)
--> Время обработки объявления: 0.88 сек.
   [Сохранено 165 строк]
[Обработка 166/418] (номер строки в файле – 38448)
--> Время обработки объявления: 1.15 сек.
[Обработка 167/418] (номер строки в файле – 38449)
--> Время обработки объявления: 0.91 сек.
[Обработка 168/418] (номер строки в файле – 38450)
--> Время обработки объявления: 0.76 сек.
[Обработка 169/418] (номер строки в файле – 38451)
--> Время обработки объявления: 0.88 сек.
[Обработка 170/418] (номер строки в файле – 38452)
--> Время обработки объявления: 0.81 сек.
   [Сохранено 170 строк]
[Обработка 171/418] (номер строки в файле – 38453)
--> Время обработки объявления: 0.93 сек.
[Обработка 172/418] (номер строки в файле – 38454)
--> Время обработки объявления: 0.85 сек.
[Обработка 173/418] (номер строки в файле – 38455)
--> Время обработки объявления: 0.71 сек.
[Обработка 174/418] (номер строки в файле – 38456)
--> Время обработки объявления: 0.91 сек.
[Обработка 175/418] (номер строки в файле – 38457)
--> Время обработки объявления: 0.73 сек.
   [Сохранено 175 строк]
[Обработка 176/418] (номер строки в файле – 38458)
--> Время обработки объявления: 0.99 сек.
[Обработка 177/418] (номер строки в файле – 38459)
--> Время обработки объявления: 0.71 сек.
[Обработка 178/418] (номер строки в файле – 38460)
--> Время обработки объявления: 0.79 сек.
[Обработка 179/418] (номер строки в файле – 38461)
--> Время обработки объявления: 1.34 сек.
[Обработка 180/418] (номер строки в файле – 38462)
--> Время обработки объявления: 0.85 сек.
   [Сохранено 180 строк]
[Обработка 181/418] (номер строки в файле – 38463)
--> Время обработки объявления: 1.01 сек.
[Обработка 182/418] (номер строки в файле – 38464)
--> Время обработки объявления: 0.90 сек.
[Обработка 183/418] (номер строки в файле – 38465)
--> Время обработки объявления: 0.78 сек.
[Обработка 184/418] (номер строки в файле – 38466)
--> Время обработки объявления: 0.72 сек.
[Обработка 185/418] (номер строки в файле – 38467)
--> Время обработки объявления: 0.76 сек.
   [Сохранено 185 строк]
[Обработка 186/418] (номер строки в файле – 38468)
--> Время обработки объявления: 0.88 сек.
[Обработка 187/418] (номер строки в файле – 38469)
--> Время обработки объявления: 0.73 сек.
[Обработка 188/418] (номер строки в файле – 38470)
--> Время обработки объявления: 0.77 сек.
[Обработка 189/418] (номер строки в файле – 38471)
--> Время обработки объявления: 0.95 сек.
[Обработка 190/418] (номер строки в файле – 38472)
--> Время обработки объявления: 1.04 сек.
   [Сохранено 190 строк]
[Обработка 191/418] (номер строки в файле – 38473)
--> Время обработки объявления: 0.88 сек.
[Обработка 192/418] (номер строки в файле – 38474)
--> Время обработки объявления: 0.78 сек.
[Обработка 193/418] (номер строки в файле – 38475)
--> Время обработки объявления: 1.09 сек.
[Обработка 194/418] (номер строки в файле – 38476)
--> Время обработки объявления: 0.79 сек.
[Обработка 195/418] (номер строки в файле – 38477)
--> Время обработки объявления: 0.87 сек.
   [Сохранено 195 строк]
[Обработка 196/418] (номер строки в файле – 38478)
--> Время обработки объявления: 1.08 сек.
[Обработка 197/418] (номер строки в файле – 38479)
--> Время обработки объявления: 0.86 сек.
[Обработка 198/418] (номер строки в файле – 38480)
--> Время обработки объявления: 0.83 сек.
[Обработка 199/418] (номер строки в файле – 38481)
--> Время обработки объявления: 0.91 сек.
[Обработка 200/418] (номер строки в файле – 38482)
--> Время обработки объявления: 0.80 сек.
   [Сохранено 200 строк]
[Обработка 201/418] (номер строки в файле – 38483)
--> Время обработки объявления: 0.83 сек.
[Обработка 202/418] (номер строки в файле – 38484)
--> Время обработки объявления: 0.85 сек.
[Обработка 203/418] (номер строки в файле – 38485)
--> Время обработки объявления: 1.00 сек.
[Обработка 204/418] (номер строки в файле – 38486)
--> Время обработки объявления: 0.80 сек.
[Обработка 205/418] (номер строки в файле – 38487)
--> Время обработки объявления: 0.89 сек.
   [Сохранено 205 строк]
[Обработка 206/418] (номер строки в файле – 38488)
--> Время обработки объявления: 0.96 сек.
[Обработка 207/418] (номер строки в файле – 38489)

In [17]:
for index1, row in attributes.iterrows():
    print(f'df.at[index, "{row["field_name_en"]}"] = {row["field_name_en"]}')

df.at[index, "housing_type"] = housing_type
df.at[index, "total_area"] = total_area
df.at[index, "living_area"] = living_area
df.at[index, "kitchen_area"] = kitchen_area
df.at[index, "ceiling_height"] = ceiling_height
df.at[index, "repair"] = repair
df.at[index, "sold_with_furniture"] = sold_with_furniture
df.at[index, "home_type"] = home_type
df.at[index, "parking"] = parking
df.at[index, "bathroom"] = bathroom
df.at[index, "year_of_construction"] = year_of_construction
df.at[index, "number_of_elevators"] = number_of_elevators
df.at[index, "floor_type"] = floor_type
df.at[index, "entrances"] = entrances
df.at[index, "heating"] = heating
df.at[index, "accident_rate"] = accident_rate
df.at[index, "balcony_loggia"] = balcony_loggia
df.at[index, "view_from_the_windows"] = view_from_the_windows
df.at[index, "gas_supply"] = gas_supply
df.at[index, "construction_series"] = construction_series
df.at[index, "about_the_entrance"] = about_the_entrance

In [117]:
import pandas as pd
file_data = "cian_extended_data.csv"
df_cian = pd.read_csv(file_data, low_memory=False)
df_new = df_cian.drop_duplicates()
df_new

,price,address,url,auction,title,rooms_count,housing_type,total_area,living_area,kitchen_area,...,highway_info,description,lat,lng,minor_owners,maternity_capital,publication_date_str,publication_date,photos_url,request_time
0,5350000,"Москва, ЮАО, р-н Даниловский, м. Автозаводская...",https://www.cian.ru/sale/flat/324994191/,False,"Продается апартаменты-студия, 16 м²",Студия,Вторичка / Апартаменты,16 м²,10 м²,5 м²,...,NaN,АПАРТАМЕНТЫ:\nПродаётся светлая и аккуратная с...,55.703885,37.652768,Нет,Не использовался,"Обновлено: вчера, 12:29",2025-12-19 12:29:00,https://images.cdn-cian.ru/images/kvartira-mos...,2025-12-20 03:40:29
1,5990000,"Москва, САО, р-н Головинский, м. Моссельмаш, С...",https://www.cian.ru/sale/flat/320317503/,False,"Продается апартаменты-студия, 16 м²",Студия,Вторичка / Апартаменты,16 м²,"13,5 м²",NaN,...,NaN,Уютная студия с новым ремонтом и мебелью в ЖК ...,55.859322,37.515874,NaN,NaN,"Обновлено: вчера, 16:25",2025-12-19 16:25:00,https://images.cdn-cian.ru/images/kvartira-mos...,2025-12-20 03:40:32
2,5380000,"Москва, ВАО, р-н Вешняки, м. Новогиреево, Вешн...",https://www.cian.ru/sale/flat/324490616/,True,"Продается 2-комн. квартира, 39 м²",2,Вторичка,39 м²,NaN,NaN,...,NaN,"Жилое помещение (квартира), кад. 77:03:000700...",55.740066,37.822882,NaN,NaN,"Обновлено: вчера, 10:40",2025-12-19 10:40:00,https://images.cdn-cian.ru/images/2718616692-1...,2025-12-20 03:40:35
3,5990000,"Москва, САО, р-н Головинский, м. Моссельмаш, С...",https://www.cian.ru/sale/flat/322151830/,False,"Продается апартаменты-студия, 15,2 м²",Студия,Вторичка / Апартаменты,"15,2 м²","12,7 м²",NaN,...,NaN,Уютная студия с новым ремонтом и мебелью в ЖК ...,55.859322,37.515874,NaN,NaN,"Обновлено: вчера, 19:55",2025-12-19 19:55:00,https://images.cdn-cian.ru/images/kvartira-mos...,2025-12-20 03:40:38
4,5500000,"Москва, ТАО (Троицкий), пос. Рогово, улица Шко...",https://www.cian.ru/sale/flat/323600775/,False,"Продается 1-комн. квартира, 32,6 м²",1,Вторичка,"32,6 м²",NaN,"7,5 м²",...,"Калужское шоссе, 59 км от МКАД, Симферопольско...",Номер в базе: 10289395.\n\n Московская прописк...,55.212647,37.072573,NaN,NaN,"Обновлено: вчера, 18:22",2025-12-19 18:22:00,https://images.cdn-cian.ru/images/2690280423-1...,2025-12-20 03:40:41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38695,2813324500,"Москва, ЦАО, р-н Пресненский, м. Баррикадная, ...",https://www.cian.ru/sale/flat/284989203/,False,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38696,1328522000,"Москва, ЦАО, р-н Пресненский, м. Краснопреснен...",https://www.cian.ru/sale/flat/322204297/,False,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38697,1328522000,"Москва, ЦАО, р-н Пресненский, м. Краснопреснен...",https://www.cian.ru/sale/flat/321207818/,False,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38698,1732170835,"Москва, ЦАО, р-н Пресненский, м. Охотный ряд, ...",https://www.cian.ru/sale/flat/300661842/,False,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38699,1732170825,"Москва, ЦАО, р-н Пресненский, м. Охотный ряд, ...",https://www.cian.ru/sale/flat/319641561/,False,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import pandas as pd
file_data = "cian_extended_data.csv"
df_cian = pd.read_csv(file_data, low_memory=False)
df_cian.url.nunique()

#анализируем длины полей в датасете
lengths = []
for col in df_cian.columns:
    max_len = df_cian[col].astype(str).str.len().max()
    lengths.append({'column': col,
                    'max_length': max_len,
                    'col_type': df_cian[col].dtype})
lengths_df = pd.DataFrame(lengths)
lengths_df

                   column  max_length col_type
0                   price          10    int64
1                 address         123   object
2                     url          40   object
3                 auction           5     bool
4                   title          53   object
5             rooms_count          16   object
6            housing_type          25   object
7              total_area           9   object
8             living_area           8   object
9            kitchen_area           8   object
10             floor_info           9   object
11         ceiling_height           7   object
12               bathroom          27   object
13         balcony_loggia          19   object
14  view_from_the_windows          15   object
15                 repair          13   object
16   year_of_construction           6  float64
17    construction_series          21   object
18    number_of_elevators          28   object
19             floor_type          14   object
20              entrances           6  float64
21     about_the_entrance          27   object
22                parking          14   object
23                heating          29   object
24          accident_rate           3   object
25             gas_supply          11   object
26    sold_with_furniture           3   object
27              home_type          19   object
28             metro_info         151   object
29           highway_info         100   object
30            description        3328   object
31                    lat          18  float64
32                    lng          17  float64
33           minor_owners           4   object
34      maternity_capital          16   object
35   publication_date_str          25   object
36       publication_date          19   object
37             photos_url        1753   object
38           request_time          19   object
39           process_time           6  float64

In [39]:
import pandas as pd
import re
import numpy as np

# ВТОРИЧКИ
def parse_data_with_patterns(text,pattern1,pattern2, numbers : bool):

    if pd.isna(text):
        return pd.Series([np.nan, np.nan])
    
    text = str(text).strip().lower()

    sovm = np.nan
    razdel = np.nan

    sovm_match = re.search(pattern1, text)
    razdel_match = re.search(pattern2, text)

    if numbers:
      if sovm_match:
          sovm = int(sovm_match.group(1))
    
      if razdel_match:
          razdel = int(razdel_match.group(1))
    
      return pd.Series([sovm, razdel])

    else:
      if sovm_match:
        sovm = 'Yes'
      if razdel_match:
        razdel = 'Yes'
      return pd.Series([sovm, razdel])

def clean_rooms_count(row):
    
    title = str(row['title']).lower()
    old_rooms = str(row['rooms_count'])
    
    #ищем долю
    ratio_pattern = r'доля|%|\d+\s*/\s*\d+'
    if re.search(ratio_pattern, title):
        return 'Доля'
        
    #многокомнатную
    if 'многоком' in title:
        return 'Многокомнатная'
        
    #перезапись свободной планировки
    if 'своб' in old_rooms.lower():
        return 'Свободная'

    return old_rooms


file_data = "cian_extended_data.csv"
df_cian = pd.read_csv(file_data, low_memory=False)


#удаляем те объявления, которые были сняты с публикации в процессе парсинга
df_cian_clean = df_cian[(df_cian['title'] != 'Страница не найдена') & (df_cian['title'] != 'Не найден')]
df_cian_clean = df_cian_clean.dropna(subset=['price'])
print(f'Удалено строк: {df_cian.url.nunique() - df_cian_clean.url.nunique()}')

#price в инт
df_cian_clean['price'] = df_cian_clean['price'].astype('Int64')



#дозаполняю доли и многокомнатные, Своб.планировка привожу к виду "Свободная"
df_cian_clean['rooms_count'] = df_cian_clean.apply(clean_rooms_count, axis=1)


#вторичка и апартаменты с пентхаусами
df_cian_clean['new_building'] = df_cian_clean['housing_type'].apply(lambda x: 'Новостройка' if 'новостр' in str(x).lower() else
                                                                              'Вторичка' if 'вторич' in str(x).lower() else np.nan)
df_cian_clean['apartment'] = df_cian_clean['housing_type'].apply(lambda x: 'Апартаменты' if 'апартам' in str(x).lower() else
                                                                            'Пентхаус' if 'пентх' in str(x).lower() else np.nan)
#del df_cian_clean['housing_type']


#всякие квадратные метры
df_cian_clean['total_area'] = df_cian_clean['total_area'].str.replace('м²','') \
                             .str.replace(',','.') \
                             .astype(float)
df_cian_clean['living_area'] = df_cian_clean['living_area'].str.replace('м²','') \
                             .str.replace(',','.') \
                             .astype(float)
df_cian_clean['kitchen_area'] = df_cian_clean['kitchen_area'].str.replace('м²','') \
                             .str.replace(',','.') \
                             .astype(float)
df_cian_clean['ceiling_height'] = df_cian_clean['ceiling_height'].str.replace('м','') \
                             .str.replace(',','.') \
                             .astype(float)


#этажность
df_cian_clean[['floor', 'total_floors']] = df_cian_clean['floor_info'].str.split(' из ', expand=True)
df_cian_clean['floor'] = df_cian_clean['floor'].astype(int)
df_cian_clean['total_floors'] = df_cian_clean['total_floors'].astype(int)
#del df_cian_clean['floor_info']

#санузлы
comb_bathroom_pattern = r'(\d+)\s*[-–]?\s*совмещен'
razdel_pattern = r'(\d+)\s*[-–]?\s*раздел'
df_cian_clean[['combined_bathroom', 'separated_bathroom']] = df_cian_clean['bathroom'].apply(lambda x: parse_data_with_patterns(x,comb_bathroom_pattern,razdel_pattern,True))
#del cian_cleaned['bathroom']

#балкон лоджия
balcony_pattern = r'(\d+)\s*[-–]?\s*балко'
loggia_pattern = r'(\d+)\s*[-–]?\s*лодж'
df_cian_clean[['balcony', 'loggia']] = df_cian_clean['balcony_loggia'].apply(lambda x: parse_data_with_patterns(x,balcony_pattern,loggia_pattern,True))
#del cian_cleaned['balcony_loggia']

#лифты
passanger_pattern = r'(\d+)\s*[-–]?\s*пассажир'
cargo_pattern = r'(\d+)\s*[-–]?\s*грузов'
df_cian_clean[['passenger_elevator', 'cargo_elevator']] = df_cian_clean['number_of_elevators'].apply(lambda x: parse_data_with_patterns(x,passanger_pattern,cargo_pattern,True))
#del df_cian_clean['number_of_elevators']

#тип перекрытий "нет информации" заменяем на Nan
df_cian_clean['floor_type'] = df_cian_clean['floor_type'].apply(lambda x: np.nan if 'нет информации' in str(x).lower() else x)

#всякое к int
df_cian_clean['entrances'] = df_cian_clean['entrances'].astype('Int64')
df_cian_clean['year_of_construction'] = df_cian_clean['year_of_construction'].astype('Int64')


#мусоропровод и консьерж
garbage_pattern = 'мусор'
concierge_pattern = 'консь'
df_cian_clean[['garbage_chute', 'concierge']] = df_cian_clean['about_the_entrance'].apply(lambda x: parse_data_with_patterns(x,garbage_pattern,concierge_pattern,False))
#del cian_cleaned['about_the_entrance']

#всякое к Д/Н
df_cian_clean['auction'] = df_cian_clean['auction'].apply(lambda x: 'Д' if x == True else 'Н')
df_cian_clean['garbage_chute'] = df_cian_clean['garbage_chute'].apply(lambda x: 'Д' if str(x).lower() == 'yes' else 
                                                                                'Н' if str(x).lower() == 'no' else np.nan)
df_cian_clean['concierge'] = df_cian_clean['concierge'].apply(lambda x: 'Д' if str(x).lower() == 'yes' else 
                                                                        'Н' if str(x).lower() == 'no' else np.nan)
df_cian_clean['accident_rate'] = df_cian_clean['accident_rate'].apply(lambda x: 'Д' if str(x).lower() == 'да' else
                                                                                'Н' if str(x).lower() == 'нет' else np.nan)
df_cian_clean['sold_with_furniture'] = df_cian_clean['sold_with_furniture'].apply(lambda x: 'Д' if str(x).lower() == 'да' else 
                                                                                            'Н' if str(x).lower() == 'нет' else np.nan)
df_cian_clean['minor_owners'] = df_cian_clean['minor_owners'].apply(lambda x: 'Д' if str(x).lower() == 'есть' else
                                                                              'Н' if str(x).lower() == 'нет' else np.nan)
df_cian_clean['maternity_capital'] = df_cian_clean['maternity_capital'].apply(lambda x: 'Д' if str(x).lower() == 'использовался' else
                                                                                        'Н' if str(x).lower() == 'не использовался' else np.nan)

#datetime
df_cian_clean['publication_date'] = pd.to_datetime(df_cian_clean['publication_date'])
df_cian_clean['request_time'] = pd.to_datetime(df_cian_clean['request_time'])


#переименую столбец
df_cian_clean = df_cian_clean.rename(columns={
    'home_type': 'house_type'
})



df_cian_clean.head()
'''df_cian_clean[(df_cian_clean['title'] == 'Продается 5/16 квартиры, 45/27,1/6 м²') |
              (df_cian_clean['title'] == 'Продается 10% квартиры, 33/27 м²') |
              (df_cian_clean['title'] == 'Продается доля, 58 м²')]'''
df_cian_clean.head(20)
df_cian_clean[df_cian_clean.address =='Москва, ЮВАО, р-н Некрасовка, м. Некрасовка, Рождественская улица, 21к5']    
df_cian_clean.info()

#порядок столбцов
df_cian_clean = df_cian_clean[['title',	'url',	'address',	'price', 'auction',	'rooms_count',	
                               #'housing_type', #check
                               'new_building',	
                               'apartment',	'total_area',	'living_area',	'kitchen_area',	'ceiling_height',
                               #'floor_info', #check
                               'floor',	'total_floors',
                               #'bathroom', #check
                               'combined_bathroom',	'separated_bathroom',
                               #'balcony_loggia', #check
                               'balcony', 'loggia',	'view_from_the_windows',	'repair',	'year_of_construction',	'construction_series',
                               #'number_of_elevators', #сheck
                               'passenger_elevator',	'cargo_elevator',	'floor_type',	'entrances',
                               #'about_the_entrance', #check
                               'garbage_chute',
                               'concierge',	'parking',	'heating',	'accident_rate', 'gas_supply', 'sold_with_furniture',
                               'house_type', 'metro_info', 'highway_info', 'description', 'lat',	'lng',
                               'minor_owners',	'maternity_capital', 'publication_date', 'request_time',	'photos_url'
]]
df_cian_clean.to_csv('cian_data_secondary_cleaned.csv',mode='w',index=False,header=True, encoding='utf-8-sig', sep=';')

Удалено строк: 24
<class 'pandas.core.frame.DataFrame'>
Index: 38676 entries, 0 to 38699
Data columns (total 52 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   price                  38676 non-null  Int64
 1   address                38676 non-null  object
 2   url                    38676 non-null  object
 3   auction                38676 non-null  object
 4   title                  38676 non-null  object
 5   rooms_count            38676 non-null  object
 6   housing_type           38676 non-null  object
 7   total_area             38676 non-null  float64
 8   living_area            28424 non-null  float64
 9   kitchen_area           35043 non-null  float64
 10  floor_info             38676 non-null  object
 11  ceiling_height         26855 non-null  float64
 12  bathroom               34472 non-null  object
 13  balcony_loggia         19542 non-null  object
 14  view_from_the_windows  23304 non-null  object
 15  repair                 35355 non-null  object
 16  year_of_construction   33916 non-null  Int64
 17  construction_series    24169 non-null  object
 18  number_of_elevators    29353 non-null  object
 19  floor_type             23611 non-null  object
 20  entrances              27414 non-null  Int64
 21  about_the_entrance     11651 non-null  object
 22  parking                27949 non-null  object
 23  heating                33963 non-null  object
 24  accident_rate          33963 non-null  object
 25  gas_supply             8025 non-null   object
 26  sold_with_furniture    13338 non-null  object
 27  house_type             27805 non-null  object
 28  metro_info             38188 non-null  object
 29  highway_info           6264 non-null   object
 30  description            38676 non-null  object
 31  lat                    38676 non-null  float64
 32  lng                    38676 non-null  float64
 33  minor_owners           1725 non-null   object
 34  maternity_capital      1735 non-null   object
 35  publication_date_str   38676 non-null  object
 36  publication_date       38676 non-null  datetime64[ns]
 37  photos_url             37823 non-null  object
 38  request_time           38676 non-null  datetime64[ns]
 39  process_time           31430 non-null  float64
 40  new_building           38676 non-null  object
 41  apartment              4921 non-null   object
 42  floor                  38676 non-null  int32
 43  total_floors           38676 non-null  int32
 44  combined_bathroom      22839 non-null  float64
 45  separated_bathroom     16357 non-null  float64
 46  balcony                9856 non-null   float64
 47  loggia                 10801 non-null  float64
 48  passenger_elevator     28537 non-null  float64
 49  cargo_elevator         18797 non-null  float64
 50  garbage_chute          11082 non-null  object
 51  concierge              778 non-null    object
dtypes: Int64(3), datetime64[ns](2), float64(13), int32(2), object(32)
memory usage: 15.5+ MB

In [77]:
parse_date_string('Обновлено: сегодня, 12:29')

'2025-12-19 12:29:00'

In [21]:

stats = df_cian.groupby('home_type', as_index=False).agg({'url': 'count'})
stats
result = ", ".join([f"{row['home_type']} - {row['url']:,}".replace(',', ' ') for _, row in stats.iterrows()])
print(result)

Блочный - 1 709, Деревянный - 4, Кирпичный - 6 478, Монолитно-кирпичный - 1 431, Монолитный - 10 601, Панельный - 7 529, Сталинский - 53

In [35]:
df_cian_clean.head(20)

,title,url,address,price,auction,rooms_count,new_building,apartment,total_area,living_area,...,metro_info,highway_info,description,lat,lng,minor_owners,maternity_capital,publication_date,request_time,photos_url
0,"Продается апартаменты-студия, 16 м²",https://www.cian.ru/sale/flat/324994191/,"Москва, ЮАО, р-н Даниловский, м. Автозаводская...",5350000,Н,Студия,Вторичка,Апартаменты,16.0,10.0,...,"Автозаводская 5 мин. (пешком), ЗИЛ 9 мин. (пеш...",NaN,АПАРТАМЕНТЫ:\nПродаётся светлая и аккуратная с...,55.703885,37.652768,Н,Н,2025-12-19 12:29:00,2025-12-20 03:40:29,https://images.cdn-cian.ru/images/kvartira-mos...
1,"Продается апартаменты-студия, 16 м²",https://www.cian.ru/sale/flat/320317503/,"Москва, САО, р-н Головинский, м. Моссельмаш, С...",5990000,Н,Студия,Вторичка,Апартаменты,16.0,13.5,...,"Моссельмаш 10 мин. (пешком), Грачёвская 19 мин...",NaN,Уютная студия с новым ремонтом и мебелью в ЖК ...,55.859322,37.515874,Н,Н,2025-12-19 16:25:00,2025-12-20 03:40:32,https://images.cdn-cian.ru/images/kvartira-mos...
2,"Продается 2-комн. квартира, 39 м²",https://www.cian.ru/sale/flat/324490616/,"Москва, ВАО, р-н Вешняки, м. Новогиреево, Вешн...",5380000,Н,2,Вторичка,NaN,39.0,NaN,...,"Новогиреево 17 мин. (пешком), Новогиреево 5 ми...",NaN,"Жилое помещение (квартира), кад. 77:03:000700...",55.740066,37.822882,Н,Н,2025-12-19 10:40:00,2025-12-20 03:40:35,https://images.cdn-cian.ru/images/2718616692-1...
3,"Продается апартаменты-студия, 15,2 м²",https://www.cian.ru/sale/flat/322151830/,"Москва, САО, р-н Головинский, м. Моссельмаш, С...",5990000,Н,Студия,Вторичка,Апартаменты,15.2,12.7,...,"Моссельмаш 10 мин. (пешком), Грачёвская 19 мин...",NaN,Уютная студия с новым ремонтом и мебелью в ЖК ...,55.859322,37.515874,Н,Н,2025-12-19 19:55:00,2025-12-20 03:40:38,https://images.cdn-cian.ru/images/kvartira-mos...
4,"Продается 1-комн. квартира, 32,6 м²",https://www.cian.ru/sale/flat/323600775/,"Москва, ТАО (Троицкий), пос. Рогово, улица Шко...",5500000,Н,1,Вторичка,NaN,32.6,NaN,...,NaN,"Калужское шоссе, 59 км от МКАД, Симферопольско...",Номер в базе: 10289395.\n\n Московская прописк...,55.212647,37.072573,Н,Н,2025-12-19 18:22:00,2025-12-20 03:40:41,https://images.cdn-cian.ru/images/2690280423-1...
5,"Продается студия, 20 м²",https://www.cian.ru/sale/flat/324712040/,"Москва, ЮВАО, р-н Некрасовка, м. Некрасовка, П...",5600000,Н,Студия,Вторичка,NaN,20.0,12.0,...,"Некрасовка 3 мин. (пешком), Лухмановская 18 ми...","Новорязанское шоссе, 12 км от МКАД, Косинское ...",Код объекта: 1958895.\nУникальное предложение ...,55.704996,37.922335,Н,Н,2025-12-18 18:26:00,2025-12-20 03:40:44,https://images.cdn-cian.ru/images/2725644747-1...
6,"Продается 1-комн. квартира, 30,8 м²",https://www.cian.ru/sale/flat/323240964/,"Москва, ТАО (Троицкий), пос. ЛМС, Центральный ...",5700000,Н,1,Вторичка,NaN,30.8,NaN,...,NaN,"Калужское шоссе, 42 км от МКАД, Варшавское шос...",Номер в базе: 10099003.\n\n Продается светлая ...,55.314407,37.176553,Н,Н,2025-12-19 17:45:00,2025-12-20 03:40:47,https://images.cdn-cian.ru/images/2677754356-1...
7,"Продается апартаменты-студия, 31,9 м²",https://www.cian.ru/sale/flat/324212999/,"Москва, ВАО, р-н Измайлово, м. Измайловская, 4...",5490000,Н,Студия,Вторичка,Апартаменты,31.9,NaN,...,"Измайловская 12 мин. (пешком), Первомайская 12...",NaN,Номер в базе: 10409187.\n\n Продаю квартиру-ст...,55.794593,37.786240,Н,Н,2025-12-19 17:43:00,2025-12-20 03:40:49,https://images.cdn-cian.ru/images/2709752757-1...
8,"Продается студия, 35 м²",https://www.cian.ru/sale/flat/324559337/,"Москва, ТАО (Троицкий), м. Троицк, с. Былово, ...",5800000,Н,Студия,Вторичка,NaN,35.0,18.0,...,"Троицк откроется в 2026 15 мин. (на машине), В...","Калужское шоссе, 27 км от МКАД, Киевское шоссе...",На продажу выставлена современная квартира-сту...,55.448393,37.245634,Н,Н,2025-12-19 05:55:00,2025-12-20 03:40:52,https://images.cdn-cian.ru/images/2722324218-1...
9,"Продается апартаменты-студия, 12,7 м²",https://www.cian.ru/sale/flat/321742295/,"Москва, САО, р-н Ховрино, м. Грачёвская, Клинс...",5600000,Н,Студия,Вторичка,Апартаменты,12.7,NaN,...,"Беломорская 18 мин. (пешком), Грачёвская 11 ми...",NaN,Номер в базе: 9806826.\n\n Продается современн...,55.868536,37.497063,Н,Н,2025-12-19 17:39:00,2025-12-20 03:40:54,https://images.cdn-cian.ru/images/2626490162-1...
10,"Продаются 2-комн. апартаменты, 56,3 м²",https://www.cian.ru/sale/flat/323201527/,"Москва, ТАО (Троицкий), Витро Вилладж База отд...",3440000,Н,2,Вторичка,Апартаменты,56.3,NaN,...,NaN,"Симферопольское шоссе, 39 км от МКАД, Варшавск...",Номер в базе: 10182479.\n\n Продается прекрасн...,55.337481,37.326240,Н,Н,2025-12-19 17:49:00,2025-12-20 03:40:57,https://images.cdn-cian.ru/images/2676378045-1...
11,"Продается студия, 16,3 м²",https://www.cian.ru/sale/flat/324783537/,"Москва, ЮВАО, р-н Некрасовка, м. Некрасовка, Р...",4800000,Н,Студия,Вторичка,NaN,16.3,NaN,...,"Некрасовка 9 мин. (пешком), Лухмановская 12 ми...","Новорязанское шоссе, 11 км от МКАД, Косинское ...",За объект уже внесли аванс\nВ продаже студия в...,55.706792,37.915741,Н,Н,2025-12-19 15:26:00,2025-12-20 03:41:01,https://images.cdn-cian.ru/images/kvartira-mos...
12,"Продаются 3-комн. апартаменты, 105,7 м²",https://www.cian.ru/sale/flat/323201520/,"Москва, ТАО (Троицкий), Витро Вилладж База отд...",5300000,Н,3,Вторичка,Апартаменты,105.7,NaN,...,NaN,"Симферопольское шоссе, 38 км от МКАД, Варшавск...",Номер в базе: 10182052.\n\n Продается прекрасн...,55.337921,37.323087,Н,Н,2025-12-19 17:49:00,2025-12-20 03:41:03,https://images.cdn-cian.ru/images/2676377983-1...
13,"Продается апартаменты-студия, 18,8 м²",https://www.cian.ru/sale/flat/320006993/,"Москва, ТАО (Троицкий), м. Троицк, Троицк, ули...",5950000,Н,Студия,Вторичка,Апартаменты,18.8,NaN,...,"Троицк откроется в 2026 20 мин. (пешком), Ольх...","Калужское шоссе, 18 км от МКАД, Киевское шоссе...",Номер в базе: 7647731.\n\n Вашему вниманию пре...,55.492217,37.314822,Н,Н,2025-12-19 18:26:00,2025-12-20 03:41:06,https://images.cdn-cian.ru/images/2625314243-1...
14,"Продается апартаменты-студия, 16 м²",https://www.cian.ru/sale/flat/324884969/,"Москва, ВАО, р-н Преображенское, м. Электрозав...",5900000,Н,Студия,Вторичка,Апартаменты,16.0,11.0,...,"Электрозаводская 11 мин. (пешком), Электрозаво...",NaN,Продаются стильные апартаменты в современном к...,55.786845,37.708706,Н,Н,2025-12-18 17:05:00,2025-12-20 03:41:09,https://images.cdn-cian.ru/images/2731694886-1...
15,"Продается 1-комн. квартира, 40,6 м²",https://www.cian.ru/sale/flat/323815180/,"Москва, ТАО (Троицкий), пос. Рогово, улица Бер...",5700000,Н,1,Вторичка,NaN,40.6,18.0,...,NaN,"Калужское шоссе, 59 км от МКАД, Симферопольско...",Номер в базе: 10339348.\n\n Продается однокомн...,55.214270,37.067543,Н,Н,2025-12-19 18:52:00,2025-12-20 03:41:11,https://images.cdn-cian.ru/images/2696283579-1...
16,"Продается апартаменты-студия, 10 м²",https://www.cian.ru/sale/flat/309052464/,"Москва, САО, р-н Ховрино, м. Грачёвская, Фести...",3500000,Н,Студия,Вторичка,Апартаменты,10.0,NaN,...,"Речной вокзал 25 мин. (пешком), Грачёвская 17 ...",NaN,СОБСТВЕННИК! Без Комиссии и Переплат! ЛУЧШЕЕ п...,55.859953,37.504232,Н,Н,2025-12-19 20:10:00,2025-12-20 03:41:14,https://images.cdn-cian.ru/images/kvartira-mos...
17,"Продается апартаменты-студия, 20,2 м²",https://www.cian.ru/sale/flat/323004532/,"Москва, САО, р-н Хорошевский, м. Беговая, 3-й ...",5800000,Н,Студия,Вторичка,Апартаменты,20.2,12.0,...,"Беговая 4 мин. (пешком), Полежаевская 18 мин. ...",NaN,Дизайнерская студия с шикарным видом на Москва...,55.772578,37.541018,Н,Н,2025-12-19 12:55:00,2025-12-20 03:41:17,https://images.cdn-cian.ru/images/2737903599-1...
18,"Продается апартаменты-студия, 11,3 м²",https://www.cian.ru/sale/flat/320247561/,"Москва, ЮВАО, р-н Нижегородский, м. Нижегородс...",4000000,Н,Студия,Вторичка,Апартаменты,11.3,4.3,...,"Нижегородская 11 мин. (пешком), Новохохловская...",NaN,Номер в базе: 9089011.\n\n Продается Апартамен...,55.729012,37.722900,Н,Н,2025-12-19 17:38:00,2025-12-20 03:41:20,https://images.cdn-cian.ru/images/2577790798-1...
19,"Продается апартаменты-студия, 27,1 м²",https://www.cian.ru/sale/flat/322368187/,"Москва, ЮАО, р-н Нагорный, м. Нагорная, Электр...",5990000,Н,Студия,Вторичка,Апартаменты,27.1,16.0,...,"Нагорная 6 мин. (пешком), Нахимовский проспект...",NaN,"СТУДИЯ ПОЛНОСТЬЮ ГОТОВА К ПРОЖИВАНИЮ, НИКАКИХ ...",55.673407,37.619567,Н,Н,2025-12-19 17:08:00,2025-12-20 03:41:23,https://images.cdn-cian.ru/images/2648230948-1...

In [ ]:

file_data_first = "cian_extended_data.csv"
file_data_second = ''
df_cian = pd.read_csv(file_data, low_memory=False)

In [ ]:
# merge новостроек и вторичек
import pandas as pd
import numpy as np

file_data_first = "cian_data_filtered.csv"
file_data_second = 'cian_data_secondary_cleaned.csv'
df_cian_first = pd.read_csv(file_data_first, low_memory=False, sep=';', encoding='cp1251')
df_cian_second = pd.read_csv(file_data_second, low_memory=False, sep=';')

#доп обработка для новостроек
#price в инт
df_cian_first['price'] = df_cian_first['price'].astype('Int64')
#в новостройках только не аукцион
df_cian_first['auction'] = 'Н'

df_cian_first['housing_type'] = df_cian_first['new_building'].fillna('').astype(str) + df_cian_first['apartment'].fillna('').astype(str)
df_cian_first['apartment'] = df_cian_first['housing_type'].apply(lambda x: 'Апартаменты' if 'апартам' in str(x).lower() else
                                                                            'Пентхаус' if 'пентх' in str(x).lower() else np.nan)
df_cian_first['new_building'] = df_cian_first['housing_type'].apply(lambda x: 'Новостройка' if 'новостр' in str(x).lower() else
                                                                              'Вторичка' if 'вторич' in str(x).lower() else np.nan)
del df_cian_first['housing_type']

#корректируем Д/Н
df_cian_first['garbage_chute'] = df_cian_first['garbage_chute'].apply(lambda x: 'Д' if str(x).lower() == 'yes' else 
                                                                                'Н' if str(x).lower() == 'no' else np.nan)
df_cian_first['concierge'] = df_cian_first['concierge'].apply(lambda x: 'Д' if str(x).lower() == 'yes' else 
                                                                        'Н' if str(x).lower() == 'no' else np.nan)
df_cian_first['minor_owners'] = df_cian_first['minor_owners'].apply(lambda x: 'Д' if str(x).lower() == 'есть' else
                                                                              'Н' if str(x).lower() == 'нет' else np.nan)
df_cian_first['maternity_capital'] = df_cian_first['maternity_capital'].apply(lambda x: 'Д' if str(x).lower() == 'использовался' else
                                                                                        'Н' if str(x).lower() == 'не использовался' else np.nan)
df_cian_first['ramp'] = df_cian_first['ramp'].apply(lambda x: 'Д' if str(x).lower() == 'есть' else
                                                              'Н' if str(x).lower() == 'нет' else np.nan)

#округляем дату до минут
#datetime
df_cian_first['publication_date'] = pd.to_datetime(df_cian_first['publication_date'], dayfirst=True)
df_cian_second['publication_date'] = pd.to_datetime(df_cian_second['publication_date'], dayfirst=False)
df_cian_first['request_time'] = pd.to_datetime(df_cian_first['request_time'], dayfirst=True)
df_cian_second['request_time'] = pd.to_datetime(df_cian_second['request_time'], dayfirst=False)

del df_cian_first['offer_date']

#оставляем только соотв тип строительства
df_cian_first = df_cian_first[df_cian_first['new_building'] == 'Новостройка']
df_cian_second = df_cian_second[df_cian_second['new_building'] == 'Вторичка']

#вручную исправляю строку, которая не распарсилась
df_cian_second.loc[df_cian_second['title'] == 'Продается 0,225 квартиры, 35 м²', 'rooms_count'] = 'Доля'
del df_cian_second['title']

df_merged = pd.concat([df_cian_second, df_cian_first], ignore_index=True)
#df_cian_second.info()

'''
for col in df_cian_first.columns:
    type_1 = df_cian_first[col].dtype
    
    if col in df_cian_second.columns:
        type_2 = df_cian_second[col].dtype
    else:
        type_2 = "НЕТ В SEC"
        
    print(f'{col:<30} | {str(type_1):<15} | {str(type_2):<15}')
'''


df_merged.info()

df_merged = df_merged[df_merged['auction'] == 'Н']
df_merged.to_csv('cian_full_data.csv',mode='w',index=False,header=True, encoding='utf-8-sig', sep=';')
df_merged.head()

df_cian_first.info()

for col in df_cian_first.columns:
    print(col)

print('----')
for col in df_cian_second.columns:
    print(col)

In [ ]:
df_merged.shape

In [ ]:
print(df_cian_first.shape, df_cian_first.url.nunique())
print(df_cian_second.shape, df_cian_second.url.nunique())
print(df_merged.shape, df_merged.url.nunique())

In [ ]:
df_cian_first

In [ ]:
duplicates = df_merged[df_merged.duplicated(subset=['url'], keep=False)]

#сортируем по URL, чтобы одинаковые квартиры стояли рядом
duplicates_sorted = duplicates.sort_values(by='url')

duplicates_sorted
duplicates_sorted.to_csv('duplicates_sorted.csv',mode='w',index=False,header=True, encoding='utf-8-sig', sep=';')